/**
 * Brief 200 — /services/sewer (the Sewer Services hub), ported verbatim from the approved package
 * (public/sewer-v2-test/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae). Generated by the Brief 200 port
 * script, then owned by hand. Do not edit copy without a brief.
 *
 * The services list (featured card + grid) is NOT here: it is the shared SEWER_SERVICES list in
 * ./services.ts, so the hub and the 9 service pages can never disagree. The No Drip Club band is the
 * shared SEWER_NDC copy.
 *
 * The one approved-copy edit (Brief 200 Track D, Marketing 2026-10-07): the package's hero call
 * button showed the test number 773-923-2106. It now renders the site's number through
 * PhoneLink/PhoneNumber like every other phone position, so WhatConverts can swap it — a second real
 * number in the body would hijack the header (Brief 185 §4.1).
 */
export const SEWER_HUB = {
  meta: {
    title: "Sewer Services in Chicago & Suburbs",
    description: "Sewer services from J. Blanton Plumbing: rodding, hydro jetting, repair, replacement, installation, camera inspection and more across Chicagoland and Central Ohio.",
  },
  hero: {
    image: {
      src: "/images/services/sewer/chicago-sewer.webp",
      alt: "J. Blanton technician working on a Chicago sewer line",
    },
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Services",
    intro: "Sewer line work isn't typical plumbing. It takes specialized equipment and a more accurate diagnosis than most repairs around your home. Hire a crew that hasn't done this before, and a simple-looking job can turn into an expensive mess once the ground is open.",
    pillsLabel: "Quick links",
    pills: [
      { href: "/emergency-plumbing", label: "Emergency Plumbing" },
      { href: "/knowledge-hub", label: "Knowledge Hub" },
      { href: "/financing", label: "Financing" },
      { href: "/help-and-support", label: "Help & Support" },
    ],
  },
  trust: {
    ariaLabel: "Why homeowners trust J. Blanton",
    items: [
      "2,000+ Installs a year",
      "No Subcontractors",
      "4.8 Stars in Google Reviews",
      "Price Match Guarantee",
    ],
  },
  services: {
    eyebrow: "Understanding the Options",
    heading: "Sewer Services We Provide",
    intro: "We handle everything from small sewer repairs to full line replacements. That includes camera inspections to pinpoint the problem and trenchless repair options that skip digging up your yard. Here's a look at what we offer.",
  },
  understanding: {
    eyebrow: "The Dirty Truth",
    heading: "Understanding Sewer Work",
    intro: "Sewer line work is the fastest-evolving corner of the trade. If you want the best results, you need a company that's always investing in advanced equipment, plus an experienced crew that knows how to use it. That's exactly what we've built:",
    tiles: [
      {
        image: "/images/services/sewer/why-us-crew-photo.webp",
        alt: "J. Blanton crew members working together on a Chicago sewer line inspection",
        heading: "A Crew With Proven Experience",
        body: "We complete 2,000+ sewer liner installs a year, more than anyone else in the market. That means surprises underground rarely catch us off guard.",
      },
      {
        image: "/images/services/sewer/why-us-tech-photo.webp",
        alt: "Blue-light curing camera view inside a Chicago sewer line",
        heading: "A Company With the Right Equipment",
        body: "We have five fully loaded trailers, so nothing waits on gear. We use blue-light curing technology, which is faster and results in stronger liners.",
      },
    ],
  },
  whyUs: {
    eyebrow: "The J. Blanton Difference",
    heading: "Why Choose Us for Sewer Services?",
    intro: "Sewer problems don't always show up right away. Issues during installation or repairs can take years to surface. That's why you need to choose a company that can stand behind their work for the long haul.",
    chart: {
      ariaLabel: "Bar chart. Share of plumbing and trades small businesses still operating: Year 1, 80 percent. Year 2, 66 percent. Year 3, 55 percent. Year 5, 45 percent. Year 10, 35 percent.",
      titleLine1: "Small Business Survival Rate:",
      titleLine2: "Plumbing/Trades",
      yLabel: "% of companies still operating",
      ticks: [0, 20, 40, 60, 80, 100],
      bars: [
        { label: "Year 1", value: 80, color: "#BC0E0E", highlight: false },
        { label: "Year 2", value: 66, color: "#BC0E0E", highlight: false },
        { label: "Year 3", value: 55, color: "#BC0E0E", highlight: false },
        { label: "Year 5", value: 45, color: "#990B0B", highlight: false },
        { label: "Year 10", value: 35, color: "#540606", highlight: true },
      ],
    },
    subheading: "Accountability in the Plumbing Industry",
    body: "The survival rate for small businesses in the plumbing industry is low. More than half of plumbing companies don't make it past five years. That means they can't return for follow-up work or be held accountable.",
    stat: 65,
    statLabel: "Of Plumbing Companies Fail Within 10 Years",
    sinceIcon: "/images/services/sewer/why-us-warranty-icon-tight.webp",
    sinceLine1: "We’ve Been Here Since 1993.",
    sinceLine2: "We’ll Be Here When You Need Us.",
  },
  financing: {
    eyebrow: "Financing",
    heading: "Fix It With Financing As Low As 0%",
    body: "We’ve partnered with trusted lenders, so you can get the service you need now and pay on your terms.",
    note: "Subject to credit approval. Rates and terms vary.",
    cta: "Ask about financing options",
  },
  map: {
    iframeTitle: "Google Map of J. Blanton Plumbing office locations across Chicagoland and Central Ohio",
    iframeSrc: "https://maps.google.com/maps?hl=en&q=J.%20Blanton%20Plumbing%2C%20Sewer%20%26%20Drain&ll=41.0%2C-85.35&z=7&ie=UTF8&iwloc=B&output=embed",
    eyebrow: "Where We Work",
    headingLine1: "Sewer Service Across",
    headingLine2: " Chicagoland and Central Ohio",
    body: "We're not limited to one neighborhood. We have offices from Northbrook to Naperville, and from Evanston to Elgin. No matter where in Chicagoland you are, we can get a crew to your sewer line.",
    link: { href: "/locations", label: "See All Locations" },
  },
  reviews: {
    eyebrow: "Customer Stories",
    heading: "Sewer Services Reviews",
    intro: "The plumbing industry has a problem: over 600,000 one-star reviews on Google, nationwide. No-shows, inflated quotes, and unlicensed work happen often enough to be the norm. We set out to be the exception. Here's what our customers say happens when we show up instead.",
    proofLabel: "Review ratings and accreditation",
    rating: "4.8",
    ratingStarsLabel: "4.8 out of 5 stars",
    ratingSub: "Average Google rating",
    bbb: {
      href: "https://www.bbb.org/us/il/morton-grove/profile/plumber/j-blanton-plumbing-0654-88664305/#sealclick",
      seal: "/images/services/sewer/bbb-seal.webp",
      sealAlt: "BBB Accredited Business seal",
      label: "Accredited business. View our BBB profile",
    },
    featured: {
      quote: "\"The technicians and plumbers involved were prompt, friendly, courteous and explained everything with the sewer lining project. The sewer lines were cleaned, repaired, and inspected before the new lining was installed. I recommend them with no reservations!\"",
      name: "Terrence Thompson",
    },
    side: [
      {
        quote: "\"Rick was on time, polite, willing to explain the whole process. Tree roots had broken the remaining clay pipes under my front lawn and ramp. Inserting a liner with a 25 year warranty was the most logical choice I could make. The job went well and quickly.\"",
        name: "Pat Martin",
      },
      {
        quote: "\"Had a great experience with J. Blanton Plumbing in all regards... I was given several options for resolution on the spot with price quotes up front... yes, J. Blanton was more expensive than everyone else, albeit... I am willing to pay a little more for great customer service and professionalism.\"",
        name: "fixedweasel",
      },
    ],
  },
  faq: {
    eyebrow: "Got Questions?",
    heading: "Frequently Asked Questions",
    items: [
      {
        q: "How do I know if I need sewer repair or just cleaning/rodding?",
        preview: "If rodding clears the drain and it stays clear, it’s usually just a clog, not pipe damage.",
        full: "If a drain is slow or backing up but clears with rodding and stays clear, it’s usually a clog, not damage to the pipe. If the same drain keeps backing up after clearing, or you’re seeing multiple symptoms at once, that’s a sign the issue is bigger than a clog. We run a camera through the line to confirm exactly what’s going on before recommending a fix.",
      },
      {
        q: "What happens during a sewer inspection?",
        preview: "We run a small camera through your line and record everything it finds, so you see exactly what’s going on.",
        full: "We run a small camera through your sewer line and record everything it finds: cracks, root intrusion, blockages, misalignment. You see the same footage we do, so you know exactly what’s wrong before we talk about how to fix it.",
      },
      {
        q: "How much does sewer service cost?",
        preview: "It depends on what’s wrong and how much work it takes. We’ll always give you a flat rate before starting.",
        full: "Cost depends on what’s actually wrong: the depth of the line, how much of it needs work, and whether we can fix it without digging. We walk you through your options and give you a flat rate before any work starts. Give us a call and we’ll tell you what it’ll take for your situation.",
      },
      {
        q: "How long does sewer repair typically take?",
        preview: "Rodding is usually same-day. Repairs and relining take longer since they involve fixing the pipe itself.",
        full: "It depends on the method. Rodding usually clears a blockage the same day. Repair or trenchless relining takes longer, since it involves fixing or replacing damaged pipe rather than just clearing it. We’ll give you a timeline specific to your line once we’ve seen what’s going on.",
      },
      {
        q: "Do you offer emergency sewer service?",
        preview: "Yes, a sewer backup doesn’t wait for business hours, so neither do we.",
        full: "Yes, a sewer backup doesn’t wait for business hours, so neither do we. If you’re seeing standing water, sewage smell, or backups into your home, call us and we’ll get someone out to you.",
      },
    ],
  },
  final: {
    eyebrow: "Get Started Today",
    heading: "Ready to Stop Worrying About Your Sewer Line?",
    body: "We've been fixing sewer lines for over 30 years, and we'll tell you exactly what's wrong before we touch anything. One call gets it handled.",
  },
} as const;

export type SewerHub = typeof SEWER_HUB;
