import type { SewerServicePage } from './types';
import { MEET_J_BLANTON_VIDEO_SCHEMA, meetJBlantonPanel } from './shared';

/**
 * Brief 200 — /hydro-jetting, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/hydro-jetting/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const HYDRO_JETTING: SewerServicePage = {
  slug: "hydro-jetting",
  meta: {
    title: "Hydro Jetting Services in Chicago",
    description: "When rodding isn't enough, hydro jetting clears grease, roots, and buildup. Camera inspection included. We show you the problem and answer all your questions.",
  },
  hero: {
    crumb: "Hydro Jetting",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Hydro Jetting",
    intro: "When a drain snake isn't enough, hydro jetting scours the pipe wall clean, and you get one flat price before we start. Serving Chicagoland and Central Ohio homeowners.",
    image: {
      src: "/images/services/sewer/hydro-jetting/hero-hydro-jetting-chicago.webp",
      alt: "J. Blanton Plumbing technician kneeling on a residential driveway in Chicago, feeding a hydro jet hose into a sewer cleanout, with a branded service truck parked at the curb behind him",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "what-is-hydro-jetting",
      tint: false,
      order: 8,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "Diagram showing how hydro jetting clears a residential sewer line, with a cross-section view of the underground pipe, jet nozzle, high-pressure water spray, and debris being flushed toward the street connection",
                    src: "/images/services/sewer/hydro-jetting/hydro-jetting-diagram.webp",
                  },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["The Basics"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What Is Hydro Jetting?"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Hydro jetting clears a sewer line with a high-pressure water stream, fed through the same cleanout access point used for rodding. A specialized nozzle sprays water in every direction as it moves through the pipe, scouring grease, scale, and roots off the entire pipe wall instead of just cutting a path through the middle. It's the fix for buildup that keeps coming back after rodding, or for roots that have worked into the pipe joints. Rodding opens the line back up. Hydro jetting cleans it.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "when-you-need-hydro-jetting",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know the Signs"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["When You Need Hydro Jetting"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 16px",
          kids: [
            "Hydro jetting clears buildup off the entire pipe wall, not just the one clog blocking it right now. Here's how to know it's time to call:",
          ],
        },
        {
          tag: "div",
          cls: "grid-auto",
          kids: [
            {
              tag: "div",
              cls: "card",
              kids: [
                {
                  tag: "h3",
                  cls: "t-h4",
                  style: "margin:0 0 8px",
                  kids: ["Buildup Has Hardened on the Pipe Wall"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Grease, scale, and sludge coat the inside of the pipe over time. A rod cuts a path through the middle, but it doesn't remove what's stuck to the walls.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "card",
              kids: [
                {
                  tag: "h3",
                  cls: "t-h4",
                  style: "margin:0 0 8px",
                  kids: ["Roots Have Worked Into the Pipe Joints"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Roots find any gap in a pipe joint and grow into the line chasing moisture. A rod clears what's blocking flow right now, but it doesn't stop what's growing at the next joint down the line.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "card",
              kids: [
                {
                  tag: "h3",
                  cls: "t-h4",
                  style: "margin:0 0 8px",
                  kids: ["The Clog Keeps Coming Back After Rodding"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Rodding breaks through the immediate blockage, but it leaves buildup on the pipe walls that the next clog catches on. Hydro jetting clears what rodding leaves behind.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-happens-when-you-call-j-blanton",
      tint: true,
      order: 20,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["The J. Blanton Difference"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What Happens When You Call J. Blanton"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 24px;max-width:66ch",
                  kids: [
                    "Nothing is worse than a plumbing service where you don't understand what you're being charged for. Here's how we work the other way.",
                  ],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px;margin-bottom:28px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["1. Camera Inspection First"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: ["We show you exactly what's built up inside, in plain language."],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["2. Honest Diagnosis"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: ["We walk you through your options: short-term and long-term."],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. Upfront Pricing"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: ["We quote you a flat rate before any money changes hands."],
                        },
                      ],
                    },
                  ],
                },
                {
                  phone: { cls: "btn btn-primary t-btn", kids: [{ icon: "phone18NoAria" }, { phoneNumber: true }] },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    meetJBlantonPanel(30),
    {
      kind: "reviews",
      order: 40,
      variant: "plain",
      eyebrow: "Customer Stories",
      heading: "Hydro Jetting Services Reviews",
      items: [
        {
          quote: "\"Andreas Pastos came out and sent a camera down to evaluate the situation. It was filled with tree roots that had found their way through the joints in the pipes. He gave us several options. Once we decided that hydro jet was our best option, our technician, Kyle Johnson, arrived quickly and thoroughly hydro jetted our sewer line with a camera attached so we could see the process.\"",
          name: "Jane Ernst",
          href: "https://maps.app.goo.gl/TZi3GyZMnG9j5Dnz6",
        },
        {
          quote: "\"I had a camera inspection as well as a Hydrojet cleaning, rod, and flush of my 70' main 6\" sewer line... The camera inspection was done by George and Raul. They were prompt, professional, and detailed with the description of the process... we were able to see together where the problems were in the main and at what specific distances. I was given several options for resolution on the spot with price quotes up front.\"",
          name: "fixedweasel",
          href: "https://maps.app.goo.gl/p3keNRv3PKhqGfop7",
        },
        {
          quote: "\"Stephen Walan has done a great job helping us to remove our kitchen sink clog using hydro jetting. He listened and answered all our questions patiently. J. Blanton's overall service and communication was good.\"",
          name: "Bhavya P.",
          href: "https://maps.app.goo.gl/kdPkhHCRsqDNVFfi6",
        },
      ],
    },
    {
      kind: "faq",
      order: 50,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "Is hydrojetting better than snaking?",
          preview: "It depends on the problem. Snaking is fast and effective for most clogs; hydro jetting is the stronger fix for hardened buildup or root intrusion.",
          full: "It depends on the problem. A drain snake breaks through a clog to restore flow. It's fast, effective, and the right call for most drain issues. Hydro jetting uses high-pressure water to scour the pipe wall clean from the inside. When buildup has hardened on the pipe wall, roots have worked into the joints, or the same clog keeps coming back after rodding, hydro jetting is the stronger fix. A camera inspection tells us which one your line actually needs.",
        },
        {
          q: "How much does it cost to hydrojet a main sewer line?",
          preview: "Cost depends on the length of the line, the severity of the buildup, and what the camera inspection finds. We quote pricing upfront.",
          full: "Hydro jetting cost depends on the length of the line, the severity of the buildup, and what the camera inspection finds. Every job starts with a diagnosis. We show you exactly what's in the pipe and give you pricing upfront before any work begins. No surprises once we get started.",
        },
        {
          q: "Will hydro jetting damage pipes?",
          preview: "Not if it's done by a professional who runs a camera first to confirm what the pipe can handle.",
          full: "Not if it's done by a professional. DIY hydro jetting equipment is widely available to rent, but without a camera inspection first, you're pressurizing a pipe you can't see, and if it's cracked, corroded, or deteriorated, that pressure makes things significantly worse. When we run the camera before every job, we know exactly what the pipe can handle before we touch anything.",
        },
        {
          q: "How long will hydro jetting last?",
          preview: "Buildup is removed completely. Root intrusion tends to return over one to three years and needs maintenance again.",
          full: "It depends on what's causing the problem. Hydro jetting removes buildup completely, which gives you significantly longer results than snaking. But if tree roots are the issue, they'll grow back over time. Most homeowners with root intrusion see results last one to three years before maintenance is needed again. Grease and mineral buildup typically stays clear longer with proper care.",
        },
        {
          q: "Can hydrojetting destroy roots?",
          preview: "It clears roots that have already worked into the line, but it can't stop new roots from growing back.",
          full: "It can cut through and flush out roots that have worked their way into pipe joints, clearing the line completely. What it can't do is stop roots from growing back. That requires repairing or relining the pipe where the intrusion is happening. The camera inspection shows exactly where the roots are entering so you know what you're dealing with before you decide.",
        },
        {
          q: "Why do plumbers not like Drano?",
          preview: "It works chemically, not mechanically, and can corrode older pipes over time without clearing buildup from the walls.",
          full: "The issue isn't that it doesn't work. It's that it works chemically, not mechanically. Drano dissolves organic material, but it can also corrode older pipes over time, especially cast iron and clay lines common in Chicago homes. It also doesn't remove buildup from pipe walls the way hydro jetting does. It just clears a path through the clog. For a slow drain or minor backup, it might buy you time. For a recurring problem, it's masking something that needs to be properly diagnosed.",
        },
      ],
    },
    { kind: "ndc", order: 60 },
    { kind: "services", order: 70 },
    {
      kind: "final",
      order: 80,
      heading: "Ready to Stop Worrying About Your Sewer Line?",
      body: "We’ve been fixing Chicago sewer lines for over 30 years, and we’ll tell you exactly what’s wrong before we touch anything. One call gets it handled.",
    },
  ],
  rail: { financingOrder: 25 },
  // Marketing 2026-10-07: the Meet J. Blanton video replaced this page's MP4 section.
  videoSchema: MEET_J_BLANTON_VIDEO_SCHEMA,
};
