import type { SewerServicePage } from './types';

/**
 * Brief 200 — /overhead-sewer-systems, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/overhead-sewer-systems/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const OVERHEAD_SEWER_SYSTEMS: SewerServicePage = {
  slug: "overhead-sewer-systems",
  meta: {
    title: "Overhead Sewer System Installation & Conversion",
    description: "Basement backing up every time it rains? We install permanent overhead sewer systems across Chicagoland and Central Ohio. Call today.",
  },
  hero: {
    crumb: "Overhead Sewer Systems",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Overhead Sewer Systems",
    intro: "Does your basement flood every time it rains hard? We install a permanent fix for homeowners across Chicagoland and Central Ohio.",
    image: {
      src: "/images/services/sewer/svc-overhead-sewer.webp",
      alt: "J. Blanton Plumbing technician installing an overhead sewer pipe along a basement ceiling",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "does-your-basement-need-an-overhead-sewer-system",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know the Signs"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Does Your Basement Need an Overhead Sewer System?"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 28px;max-width:66ch",
          kids: [
            "There are several signs your basement needs an overhead sewer system. Some are subtle. Others aren’t. Here’s what to look for, from mild to severe:",
          ],
        },
        {
          tag: "div",
          style: "display:grid;grid-template-columns:repeat(auto-fit,minmax(min(260px,100%),1fr));gap:24px",
          kids: [
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Water at the Floor Drain When It Rains Hard"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "A little backup at the floor drain during heavy rain, gone by morning. Easy to ignore. It’s usually the first sign your sewer connection can’t keep up.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Rodding That Stops Working"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "The line gets ",
                    {
                      tag: "a",
                      style: "color:var(--c-carmine)",
                      attrs: { href: "/sewer-rodding" },
                      kids: ["rodded"],
                    },
                    ", it clears, and a few weeks later the backup returns. That’s not a clogging problem anymore. It’s a sign the connection itself is the limit.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["A Backup That’s Already Caused Damage"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Sewage in a finished basement. Ruined flooring, drywall, belongings. At this point, another temporary fix isn’t worth the risk of round two.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "how-an-overhead-sewer-system-works",
      tint: true,
      order: 20,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["The Basics"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["How an Overhead Sewer System Works"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 16px",
                  kids: [
                    "An overhead sewer system stops flooding when the street sewer can’t keep up, using gravity for the upper floors and a pump for everything below it. Here’s how it fits together:",
                  ],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 16px",
                  kids: [
                    "Every drain below the street sewer’s flow line, like your floor drain, a basement bathroom, or a laundry line, normally relies on gravity to reach the sewer. An overhead sewer system reroutes those drains into a sump pit instead.",
                  ],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 16px",
                  kids: [
                    "An ejector pump lifts that wastewater up to a line above flood level, where a check valve keeps it from flowing back down. From there, gravity carries it the rest of the way to the street sewer, the same as every drain upstairs.",
                  ],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "In short, it doesn’t replace your current drainage, it adds to it: extra capacity, positioned somewhere floodwater can’t reach. If you want the full picture, ",
                    {
                      tag: "a",
                      style: "color:var(--c-carmine)",
                      attrs: {
                        href: "/knowledge-hub/45468-stop-basement-floods-how-overhead-sewer-systems-protect-homes-in-chicagos-north-and-northwest-side",
                      },
                      kids: ["we’ve written a guide that walks through it"],
                    },
                    ".",
                  ],
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "Diagram of an overhead sewer system: basement drains feed an ejector pump that lifts wastewater above flood level to the main sanitary line, with a separate sump pump for groundwater",
                    src: "/images/services/sewer/overhead-sewer-systems/overhead-sewer-systems-diagram.webp",
                    loading: "lazy",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "overhead-sewer-installation",
      tint: false,
      order: 30,
      body: [
        {
          tag: "span",
          cls: "t-eyebrow",
          style: "color:var(--c-carmine)",
          kids: ["New Construction & Older Homes"],
        },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Overhead Sewer Installation"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 16px;max-width:66ch",
          kids: [
            "An overhead sewer installation is for new construction or a home that’s never had the system, not a home upgrading an inadequate one. Here’s how each applies:",
          ],
        },
        {
          tag: "ul",
          style: "margin:0 0 16px;padding-left:20px;display:flex;flex-direction:column;gap:10px;max-width:66ch",
          kids: [
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate)",
              kids: [
                { tag: "strong", style: "color:var(--c-midnight)", kids: ["You’re building new:"] },
                " the sump pit, ejector pump, and check valve get designed in from day one, before any pipe goes in the ground.",
              ],
            },
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate)",
              kids: [
                {
                  tag: "strong",
                  style: "color:var(--c-midnight)",
                  kids: ["Your home was never built with one:"],
                },
                " plenty of older Chicagoland and Central Ohio homes run on a straight gravity connection with no overhead system at all.",
              ],
            },
          ],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 16px;max-width:66ch",
          kids: [
            "Either way, the goal is the same: raise your basement’s drains above the level the street sewer can reach, not the rest of the house.",
          ],
        },
        {
          tag: "div",
          style: "background:#F1E8DC;border-left:4px solid var(--c-carmine);border-radius:8px;padding:14px 18px;max-width:66ch",
          kids: [
            {
              tag: "p",
              cls: "t-body-sm",
              style: "color:var(--c-midnight);margin:0",
              kids: [
                "Some jurisdictions require an overhead sewer system in specific situations. We can tell you what applies to your property.",
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "overhead-sewer-conversion-for-older-homes",
      tint: true,
      order: 40,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["When Rodding Isn’t Enough"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Overhead Sewer Conversion for Older Homes"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 16px",
                  kids: [
                    "Overhead sewer conversion is for a home whose connection has reached its limit, not one still solvable with a rodding visit. Here’s what changes:",
                  ],
                },
                {
                  tag: "ul",
                  style: "margin:0 0 16px;padding-left:20px;display:flex;flex-direction:column;gap:10px",
                  kids: [
                    {
                      tag: "li",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate)",
                      kids: [
                        {
                          tag: "strong",
                          style: "color:var(--c-midnight)",
                          kids: ["Repeat backups on your current setup:"],
                        },
                        " you’ve had it rodded or cleaned, maybe more than once, and it keeps coming back. Converting ends the cycle instead of scheduling another temporary fix.",
                      ],
                    },
                    {
                      tag: "li",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate)",
                      kids: [
                        {
                          tag: "strong",
                          style: "color:var(--c-midnight)",
                          kids: ["An outdated or undersized existing system:"],
                        },
                        " some older setups were sized for the storms of their era, not today’s. Converting brings your connection up to what your home actually needs now.",
                      ],
                    },
                  ],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Either way, conversion is the permanent version of the same fix. It’s not a strike against rodding or maintenance, it’s for when the underlying connection is the actual problem, not the clog.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "Two plumbers mounting new overhead sewer piping along a basement ceiling during an overhead sewer conversion",
                    src: "/images/services/sewer/overhead-sewer-systems/overhead-sewer-system-conversion.webp",
                    loading: "lazy",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "overhead-sewer-vs-sump-pump-vs-backwater-valve",
      tint: false,
      order: 50,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know Your Options"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Overhead Sewer vs. Sump Pump vs. Backwater Valve"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 24px;max-width:70ch",
          kids: [
            "A sump pump, a backwater valve, and an overhead sewer system each solve a different basement water problem, and only one of them fixes a sewer connection that’s reached its limit. Here’s how they compare:",
          ],
        },
        {
          tag: "div",
          style: "background:#FFFFFF;border-radius:14px;padding:clamp(16px,3vw,32px);box-shadow:0 4px 20px rgba(10,27,46,0.08)",
          kids: [
            {
              tag: "div",
              cls: "ss-compare-wrap",
              kids: [
                {
                  tag: "table",
                  cls: "ss-compare",
                  kids: [
                    {
                      tag: "thead",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "col" } },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Sump Pump"] },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Backwater Valve"] },
                            {
                              tag: "th",
                              cls: "ss-compare-hi",
                              attrs: { scope: "col" },
                              kids: ["Overhead Sewer System"],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      tag: "tbody",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "row" }, kids: ["What It Solves"] },
                            {
                              tag: "td",
                              attrs: { "data-label": "Sump Pump" },
                              kids: ["Groundwater seeping in through the foundation or under the slab."],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Backwater Valve" },
                              kids: ["Sewage flowing backward into the house through the drain line."],
                            },
                            {
                              tag: "td",
                              cls: "ss-compare-hi",
                              attrs: { "data-label": "Overhead Sewer System" },
                              kids: [
                                "A sewer connection that backs up because it sits too low relative to the street sewer.",
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "row" }, kids: ["How It Works"] },
                            {
                              tag: "td",
                              attrs: { "data-label": "Sump Pump" },
                              kids: ["Collects groundwater in a pit and pumps it outside, away from the house."],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Backwater Valve" },
                              kids: [
                                "A flap in the line closes automatically when flow reverses, blocking sewage from coming back in.",
                              ],
                            },
                            {
                              tag: "td",
                              cls: "ss-compare-hi",
                              attrs: { "data-label": "Overhead Sewer System" },
                              kids: [
                                "Reroutes the low drains into a sump pit, then an ejector pump lifts that wastewater above flood level before it reaches the street sewer.",
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "row" }, kids: ["When It’s Enough"] },
                            {
                              tag: "td",
                              attrs: { "data-label": "Sump Pump" },
                              kids: [
                                "When the problem is groundwater, not sewage. It doesn’t touch a sewer backup at all.",
                              ],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Backwater Valve" },
                              kids: [
                                "When your plumbing sits high enough above the street sewer for a passive valve to do the job. Drains stay unusable while it’s closed.",
                              ],
                            },
                            {
                              tag: "td",
                              cls: "ss-compare-hi",
                              attrs: { "data-label": "Overhead Sewer System" },
                              kids: [
                                "When a passive valve isn’t enough. Your plumbing sits low enough that only actively raising the connection solves it for good.",
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-happens-when-you-call-j-blanton",
      tint: true,
      order: 60,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["The J. Blanton Difference"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What Happens When You Call J. Blanton"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 24px;max-width:66ch",
                  kids: [
                    "We answer calls 24/7, even on weekends and holidays. Once you schedule a visit, we start with a thorough look at your property, not a sales pitch.",
                  ],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px;margin-bottom:28px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["1. Honest Diagnosis"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "We walk the drainage, lay out every option, and let you decide before we do any work.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["2. Upfront Pricing"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "You get a flat rate before any money changes hands. No pressure to decide on the spot.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. Guaranteed Work"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "We stand behind every job we perform. Every overhead sewer conversion gets tested before we leave, not just installed.",
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  phone: { cls: "btn btn-primary t-btn", kids: [{ icon: "phone18NoAria" }, { phoneNumber: true }] },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "see-how-an-overhead-sewer-system-stops-the-backu",
      tint: false,
      order: 70,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [{ video: { kind: "youtube", id: "ZDFzUtjBUCk", title: "Meet J. Blanton Plumbing" } }],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Meet J. Blanton"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Big Enough to Get the Job Done, Small Enough to Care"],
                },
                {
                  tag: "p",
                  cls: "t-body",
                  style: "color:var(--c-slate);margin:0;max-width:66ch",
                  kids: [
                    "We’ve grown a lot since 1993, but the way we work hasn’t changed. Here’s a closer look at who we are.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "reviews",
      order: 80,
      variant: "link",
      eyebrow: "Customer Stories",
      heading: "Overhead Sewer System Reviews",
      items: [
        {
          quote: "\"We had Scott and Payton come by and give us a camera review of our sewer and discuss the different remedies for making sure we didn't have any backups in the future. They were very thorough and knowledgeable and super nice guys.\"",
          name: "Christine Wynn",
          href: "https://maps.app.goo.gl/F7Y2DQF3gJcTdaps5",
        },
        {
          quote: "\"We've used J Blanton before [...] Dave and Alexis were on site and prepared to deal with the muck and the troubles. [...] We did really appreciate their efforts, their openness and keeping us apprised of everything going on, the ups and downs of different options and really trying to be budget conscious. Will definitely use them again if the need should arise.\"",
          name: "Siriss Toth",
          href: "https://maps.app.goo.gl/hNPVFu8RcjxUAEq49",
        },
        {
          quote: "\"Andrew was out in about and hour and fixed our sewer back up in less than that, fire significantly cheaper than any other place we've used! Thank you!\"",
          name: "Crystal Ritchie",
          href: "https://maps.app.goo.gl/pzt6S1r2AkvwXg2J7",
        },
      ],
    },
    {
      kind: "faq",
      order: 90,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "How do I know if I need an overhead sewer system?",
          preview: "Start with how often it happens and how bad it's gotten. An occasional backup is an early sign, a recurring one is a bigger sign.",
          full: "Start with how often it happens and how bad it's gotten. An occasional backup at the floor drain during heavy rain is an early sign. If you've had the line rodded and the backup keeps coming back, that's a sign the connection itself can't keep up. If it's already caused real damage, a flooded basement, sewage in your belongings, that's the clearest sign of all. Any of these is worth a property assessment to see what your home actually needs.",
        },
        {
          q: "What's the difference between an overhead sewer system and a sump pump or backwater valve?",
          preview: "A sump pump handles groundwater, a backwater valve blocks backflow. An overhead sewer system actively raises your drainage above flood level.",
          full: "A sump pump handles groundwater seeping in through your foundation, a different problem than a sewer backup entirely. A backwater valve blocks sewage from flowing back into the house, and works well when your plumbing sits high enough above the street sewer for that to be enough on its own. An overhead sewer system is the option when it isn't: it actively raises your basement's drainage above the level the street sewer can reach, instead of just blocking the backflow.",
        },
        {
          q: "How long does overhead sewer installation take?",
          preview: "Most overhead sewer installations take 2 to 5 days, depending on your home's layout and connection routing.",
          full: "Most overhead sewer installations take 2 to 5 days, depending on your home's layout and how the connection needs to be routed.",
        },
        {
          q: "What happens during an overhead sewer installation?",
          preview: "It starts with a property assessment, then we design the setup, check local code, install it, and test the pump before we call it done.",
          full: "It starts with the property assessment you'd get on any visit, a look at your drainage and where the connection sits relative to the street sewer. From there, we design the setup for your home, check what local code requires, do the installation, and test the pump and connection before we call it done.",
        },
        {
          q: "How much does an overhead sewer system cost?",
          preview: "Cost depends on a few things specific to your home. We'll walk through it all with you and give you a flat rate before any work begins.",
          full: "Cost depends on a few things specific to your home: how deep the connection needs to go, your home's layout, whether an ejector pit is already in place or needs to be added, and how easy the work area is to access. We'll walk through all of that with you and give you a flat rate before any work begins.",
        },
        {
          q: "Is an overhead sewer system required by code in Chicago?",
          preview: "Some jurisdictions require it in specific situations, but there's no single blanket rule across every city we serve.",
          full: "Some jurisdictions require an overhead sewer system in specific situations, but there's no single blanket rule across every city we serve. We can tell you exactly what applies to your property during your assessment.",
        },
      ],
    },
    { kind: "ndc", order: 100 },
    { kind: "services", order: 110 },
    {
      kind: "final",
      order: 120,
      heading: "Ready to Stop Worrying About Your Sewer Line?",
      body: "We’ve been fixing sewer lines for over 30 years, and we’ll tell you exactly what’s wrong before we touch anything. One call gets it handled.",
    },
  ],
  rail: { financingOrder: 65 },
  videoSchema: {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "Meet J. Blanton Plumbing",
    description: "J. Blanton Plumbing delivers fast, reliable, same-day plumbing service across Chicago and the surrounding suburbs.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZDFzUtjBUCk/maxresdefault.jpg",
    uploadDate: "2025-05-21T07:47:39-07:00",
    duration: "PT47S",
    contentUrl: "https://www.youtube.com/watch?v=ZDFzUtjBUCk",
    embedUrl: "https://www.youtube.com/embed/ZDFzUtjBUCk",
  },
};
