import type { SewerServicePage } from './types';

/**
 * Brief 200 — /sewer-rodding, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/sewer-rodding/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const SEWER_RODDING: SewerServicePage = {
  slug: "sewer-rodding",
  meta: {
    title: "Sewer Rodding in Chicago & the Suburbs",
    description: "Sewer backing up into your basement? We rod sewer lines across Chicago and the suburbs, with the price confirmed before work starts. Same-day service.",
  },
  hero: {
    crumb: "Sewer Rodding",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Rodding",
    intro: "We show you exactly what's clogging your line on camera, then quote one flat price before we rod it clear. Serving Chicagoland and Central Ohio homeowners.",
    image: {
      src: "/images/services/sewer/sewer-rodding-front-yard.webp",
      alt: "J. Blanton plumber feeding the cable from a drum rodding machine into an outdoor sewer cleanout in a front yard",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "what-is-sewer-rodding",
      tint: false,
      order: 8,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "Diagram showing how sewer rodding works, with a rodding cable fed through a cleanout access point into the main sewer line and a cutting head clearing the blockage toward the street connection",
                    src: "/images/services/sewer/sewer-rodding/sewer-rodding-diagram.webp",
                  },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["The Basics"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What Is Sewer Rodding?"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Sewer rodding clears a blocked main line with a long, flexible steel cable fed through a cleanout access point. A cutting head on the end breaks through roots, grease, and debris and pushes the blockage toward the street connection, restoring flow through the pipe. It’s the standard first fix for a clogged or backed-up sewer line. For most homes, it’s the only fix needed.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-we-do-differently",
      tint: true,
      order: 20,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["The J. Blanton Difference"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What We Do Differently"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 24px;max-width:66ch",
                  kids: [
                    "Most customers say the worst part of calling a plumber isn't the clog. It's wondering whether a simple fix turns into a rebuild you didn't need. Here's how we do things differently.",
                  ],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px;margin-bottom:28px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["1. Camera Inspection Included"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: ["Nobody tells you there's a problem you can't see for yourself."],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["2. Upfront Pricing. No Upsells."],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "You get a written quote before any work begins. If the camera finds more than a standard rod-out, you decide what happens next.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. Fully Equipped"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: ["Our trucks carry the rod, the camera, and more. We can do it all in one visit."],
                        },
                      ],
                    },
                  ],
                },
                {
                  phone: { cls: "btn btn-primary t-btn", kids: [{ icon: "phone18NoAria" }, { phoneNumber: true }] },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "when-you-need-sewer-rodding",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know the Signs"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["When You Need Sewer Rodding"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 28px;max-width:66ch",
          kids: [
            "Sewer rodding fixes a blocked or clogged main line, not a minor clog. Here’s how to know it’s time to call:",
          ],
        },
        {
          tag: "div",
          cls: "grid-auto",
          kids: [
            {
              tag: "div",
              cls: "card",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0 0 8px", kids: ["You Have an Active Backup"] },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Water or sewage coming up through a basement floor drain or laundry drain means your main line is blocked. Call now for same-day emergency rodding, evenings, weekends, and holidays.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "card",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0 0 8px", kids: ["Your Line Keeps Backing Up"] },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "If you’ve had your sewer rodded more than once in the past year, roots or a pipe defect are likely growing back between visits.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "card",
              kids: [
                {
                  tag: "h3",
                  cls: "t-h4",
                  style: "margin:0 0 8px",
                  kids: ["Tried a Snake and It Didn’t Work?"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "A handheld drain snake can clear a sink or tub drain, but it doesn’t have the reach or cutting power to break through a main sewer line clog.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "considering-diy-sewer-rodding",
      tint: false,
      order: 30,
      body: [
        {
          tag: "div",
          style: "max-width:66ch;margin:0 0 24px",
          kids: [
            { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Thinking About DIY?"] },
            { tag: "h2", cls: "t-h2", style: "margin:12px 0 16px", kids: ["Considering DIY Sewer Rodding?"] },
            {
              tag: "p",
              cls: "t-body",
              style: "color:var(--c-slate);margin:0",
              kids: [
                "Hardware stores sell sewer rodding equipment. For small fixes, it's sometimes all you need. But here are 3 things you should know before reaching for one of these tools.",
              ],
            },
          ],
        },
        {
          video: {
            kind: "mp4",
            src: "https://d1ze053a37fps5.cloudfront.net/uploads/cms/sewer-v2-test/video-3-things-before-diy.mp4",
            poster: "/images/services/sewer/sewer-rodding/video-poster.jpg",
            fallback: "Your browser does not support embedded video. Call {phone} to talk to a technician instead.",
          },
        },
      ],
    },
    {
      kind: "reviews",
      order: 40,
      variant: "plain",
      eyebrow: "Customer Stories",
      heading: "Sewer Rodding Services Reviews",
      items: [
        {
          quote: "\"Edgar is a fantastic tech and was extremely professional and fantastic to work with. He was upfront and allowed me to view the issues from the camera before any money changed hands. He had multiple suggestions on how to further prevent issues, but was never pushy on trying to sell additional fixes. [...] We’ve used several plumbing companies in the past, but Edgar was well above the rest.\"",
          name: "Jon Ricco",
          href: "https://maps.app.goo.gl/LutNjGckvrsqCkcE9",
        },
        {
          quote: "\"I had an exceptional experience with Andreas from J. Blanton Plumbing. He came out to perform a camera inspection of my sewer line and was incredibly professional, thorough, and knowledgeable. He took the time to walk me through everything on the screen, explained each detail clearly, and answered all my questions with patience and honesty. Andreas went above and beyond, and I couldn't be happier with the level of service he provided. Highly recommended.\"",
          name: "Jason Newman",
          href: "https://maps.app.goo.gl/7D7wUWTsWN3fc3hZ6",
        },
        {
          quote: "\"So it's Christmas Eve and my sewer is backed up 😭. J. Blanton did not hesitate or cancel my appointment. George and Mike were excellent! They were not rushed, answered all my questions. Very knowledgeable and honest, which goes a long way especially as a first time home owner. Their pricing is very reasonable compared to other companies and professionalism exceeded expectations.\"",
          name: "Betty Knows",
          href: "https://maps.app.goo.gl/Frag5JYpxQLVZBJg8",
        },
      ],
    },
    {
      kind: "faq",
      order: 50,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "How much does it cost to rod a sewer line?",
          preview: "Cost depends on the severity of the blockage and how accessible your cleanout is. We always quote a flat price before any work starts.",
          full: "Sewer rodding costs vary depending on the severity of the blockage and how accessible your cleanout is. We give you a flat quote before any work starts, so you'll know exactly what you're paying before your tech touches a tool. If the camera inspection reveals something beyond a standard rodding job, your tech walks you through what they found and provides a separate written estimate on the spot.",
        },
        {
          q: "How often should you rod out your sewer line?",
          preview: "For Chicago-area homes with older clay pipes or mature trees near the line, annual rodding is the standard recommendation.",
          full: "For Chicago-area homes with older clay pipes or mature trees near the sewer line, annual rodding is the standard recommendation. Homes with a history of root intrusion may benefit from rodding every six months. If you've never had your line rodded and your home is more than 30 years old, a single camera inspection will tell you whether you need to put it on a schedule.",
        },
        {
          q: "What happens during a sewer rodding appointment?",
          preview: "We run a camera through the line first so you can see the blockage, then rod it clear at the flat price we quoted before starting.",
          full: "Your technician starts by running a camera through the line to see exactly what's causing the backup, roots, grease, a pipe belly, whatever it is. You see the footage before any work begins. Once you know what you're dealing with, you get a flat price for the rodding, and it doesn't change once work starts. If the camera turns up something beyond a standard rod-out, your tech explains what they found and gives you a separate estimate before doing anything more.",
        },
        {
          q: "Will a snake unclog a sewer line?",
          preview: "A professional-grade sewer rod will clear most residential clogs. A handheld hardware-store snake typically won't.",
          full: "A professional-grade sewer rod (sometimes called a power snake) will clear most residential sewer line clogs. A handheld drain snake from a hardware store typically won't. It's designed for sink and tub drains, not the 4-inch or 6-inch main sewer pipe. If you've already tried a hardware-store snake without success, the problem is in the main line and needs professional rodding equipment.",
        },
        {
          q: "What are common sewer line problems?",
          preview: "Tree root intrusion, grease and sediment buildup, pipe bellies, and deterioration of older clay or cast-iron pipes.",
          full: "The most common residential sewer line issues are tree root intrusion, grease and sediment buildup, pipe bellies (low spots where water pools), and deterioration of older clay or cast-iron pipes. In Chicago specifically, freeze-thaw cycles and soil shifting add stress to aging pipes. A camera inspection during a routine rodding visit identifies which of these you're dealing with before they cause a full backup.",
        },
        {
          q: "Do I need sewer rodding or hydro jetting?",
          preview: "Rodding clears the blockage and restores flow. Hydro jetting scours the whole pipe wall clean, which matters if buildup keeps coming back.",
          full: "Rodding breaks through roots, debris, or a clog and restores flow fast, it's the right call for a first-time backup or a line that's never been serviced. Hydro jetting scours the entire pipe wall clean, not just the blockage, so if you've had the same line rodded more than once in the past year, jetting is worth discussing with your technician.",
        },
      ],
    },
    { kind: "ndc", order: 60 },
    { kind: "services", order: 70 },
    {
      kind: "final",
      order: 80,
      heading: "Ready to Stop Worrying About Your Sewer Line?",
      body: "We’ve been fixing Chicago sewer lines for over 30 years, and we’ll tell you exactly what’s wrong before we touch anything. One call gets it handled.",
    },
  ],
  rail: { financingOrder: 25 },
};
