import type { SewerServicePage } from './types';

/**
 * Brief 200 — /sewer-line-replacement, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/sewer-line-replacement/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const SEWER_LINE_REPLACEMENT: SewerServicePage = {
  slug: "sewer-line-replacement",
  meta: {
    title: "Sewer Line Replacement",
    description: "Not sure if it's a repair or a full replacement? We show you the camera footage and explain the difference before recommending either. Call today.",
  },
  hero: {
    crumb: "Sewer Line Replacement",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Line Replacement",
    intro: "A full sewer line replacement is a big call, and you shouldn't have to take it on faith. We show you the camera footage, explain why repair won't hold, and walk through your options before anything gets dug up.",
    image: {
      src: "/images/services/sewer/svc-sewer-replacement.webp",
      alt: "J. Blanton Plumbing technician guiding a hose into a sewer line access point during a replacement job",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "signs",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know the Signs"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Does Your Sewer Line Need Full Replacement?"],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:0 0 28px;max-width:66ch",
          kids: [
            "Full replacement means a new line, not another patch or repair on the same section. Here's how to know you're actually at that point:",
          ],
        },
        {
          tag: "div",
          style: "display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:24px",
          kids: [
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Repairs Keep Failing on the Same Section"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm pv-mute",
                  style: "margin:0",
                  kids: [
                    "A section that's already been patched or relined and is still failing has run out of good pipe left to repair. Another patch just buys a little time.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Cracking or Root Intrusion Runs the Length of the Line"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm pv-mute",
                  style: "margin:0",
                  kids: [
                    "When camera footage shows damage spread across most of the pipe, not just one weak spot, lining or patching a single section won't fix what's failing everywhere else.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["The Pipe Has Collapsed or a Section Is Offset"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm pv-mute",
                  style: "margin:0",
                  kids: [
                    "A collapsed or badly offset pipe can't be patched back into shape. Water isn't moving through it the way it should, and a repair won't change that.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "repair-or-replacement",
      tint: true,
      order: 20,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["How We Decide"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Repair or Replacement? How to Tell the Difference"],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:0 0 28px;max-width:66ch",
          kids: [
            "The line between a repair and a full replacement usually comes down to how much of the pipe is affected, not just what's wrong with it. Here's how the two usually compare:",
          ],
        },
        {
          tag: "div",
          style: "background:#FFFFFF;border-radius:14px;padding:clamp(16px,3vw,32px);box-shadow:0 4px 20px rgba(10,27,46,0.08)",
          kids: [
            {
              tag: "div",
              cls: "ss-compare-wrap",
              kids: [
                {
                  tag: "table",
                  cls: "ss-compare",
                  kids: [
                    {
                      tag: "thead",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "col" }, kids: ["Repair Usually Holds"] },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Full Replacement Is Likely"] },
                          ],
                        },
                      ],
                    },
                    {
                      tag: "tbody",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Repair Usually Holds" },
                              kids: [
                                "One confirmed crack, joint separation, or root intrusion on camera, isolated to a single point",
                              ],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Full Replacement Is Likely" },
                              kids: ["Cracking or root intrusion running across most of the pipe's length"],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Repair Usually Holds" },
                              kids: ["First time this section has needed attention"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Full Replacement Is Likely" },
                              kids: ["The same section has already been repaired and is still failing"],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Repair Usually Holds" },
                              kids: [
                                "Slow drains, gurgling, or backups that clear once we rod or fix the specific spot",
                              ],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Full Replacement Is Likely" },
                              kids: ["Backups that keep coming back no matter how many times the line is cleared"],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Repair Usually Holds" },
                              kids: ["The rest of the pipe is structurally sound around the damaged area"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Full Replacement Is Likely" },
                              kids: ["The pipe has collapsed, or a section is offset"],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:20px 0 0;max-width:66ch",
          kids: [
            "A ",
            { tag: "a", attrs: { href: "/sewer-camera-inspection" }, kids: ["camera inspection"] },
            " is what turns this from a guess into an answer, and we run one before recommending either.",
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-we-do-differently",
      tint: false,
      order: 30,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["The J. Blanton Difference"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What We Do Differently"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm pv-mute",
                  style: "margin:0 0 24px;max-width:66ch",
                  kids: [
                    "The worst thing about hearing \"you need a full replacement\" is not knowing if that's actually true. Here's how we make sure it is:",
                  ],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px;margin-bottom:28px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["1. Camera Evidence Before Any Recommendation"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "We run a camera down the line before we ever say the word replacement. You see the same footage we do, so neither of us is calling it on a guess.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["2. Trenchless Options Explained First"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "Digging up the whole yard isn't automatic. If a trenchless method fits your pipe's condition, we'll explain it before assuming a full dig is the only way.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["3. A Transparent Process From Start to Finish"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "You'll know what's happening at each step, from the initial inspection through the day the job's done, not just at the beginning and the end.",
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  phone: { cls: "btn btn-primary t-btn", kids: [{ icon: "phone18" }, { phoneNumber: true }] },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "video",
      tint: true,
      order: 40,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [{ video: { kind: "youtube", id: "ZDFzUtjBUCk", title: "Meet J. Blanton Plumbing" } }],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Meet J. Blanton"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Big Enough to Get the Job Done, Small Enough to Care"],
                },
                {
                  tag: "p",
                  cls: "t-body",
                  style: "color:var(--c-slate);margin:0;max-width:66ch",
                  kids: [
                    "We’ve grown a lot since 1993, but the way we work hasn’t changed. Here’s a closer look at who we are.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "reviews",
      order: 50,
      variant: "cap",
      eyebrow: "Customer Stories",
      heading: "Sewer Line Replacement Reviews",
      items: [
        {
          quote: "\"This was a complex installation and re-piping. Matt was helpful, answered my questions and did clean and well-executed piping. He was diligent and efficient and maintained a clean work area. Very impressed.\"",
          name: "William Moyer",
          href: "https://maps.app.goo.gl/SFK8EFTRNEHpRCK28",
        },
        {
          quote: "\"They do their best [...] and show us the incredible video of the pipes, but we need to replace the main pipe or do (what I call a 'fancy and new technology') liner. We chose the latter.\"",
          name: "Karyn Soerens",
          href: "https://maps.app.goo.gl/XRobNoJLgzoj92Wr9",
        },
        {
          quote: "\"They tackled a very challenging pipe replacement job in our basement [...] professional, skilled, and incredibly thorough [...] always took the time to explain what they were doing and why.\"",
          name: "Rich Kings",
          href: "https://maps.app.goo.gl/S8d3zRHrXPSsgs3F8",
        },
      ],
    },
    {
      kind: "ndc",
      order: 60,
      body: "Prevent catastrophes before they disrupt your life. The No Drip Club ensures your waste and sewer lines are monitored and serviced regularly by our absolute best.",
    },
    { kind: "services", order: 70 },
    {
      kind: "faq",
      order: 80,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "What's the difference between sewer line repair and replacement?",
          preview: "Repair fixes a specific problem, a crack, a joint, a root intrusion, in one section of the pipe.",
          full: [
            "Repair fixes a specific problem, a crack, a joint, a root intrusion, in one section of the pipe. Full replacement puts in a new line because too much of the old one is damaged, or it's already failed. We run a camera down the line first and can tell you which one you're actually looking at. Our ",
            { tag: "a", attrs: { href: "/sewer-repair" }, kids: ["Sewer Repair"] },
            " page covers what repair looks like if that ends up being the better fit.",
          ],
        },
        {
          q: "How long does sewer line replacement take?",
          preview: "It depends on the length of the line, how deep it's buried, and whether we're using a trenchless method or a full excavation.",
          full: "It depends on the length of the line, how deep it's buried, and whether we're using a trenchless method or a full excavation. Trenchless is usually faster than digging up the yard, but the exact timeline depends on your line's condition. We'll walk you through a realistic timeline once we've seen the camera footage.",
        },
        {
          q: "Do I have to dig up my yard, or is trenchless an option?",
          preview: "Not always.",
          full: [
            "Not always. ",
            { tag: "a", attrs: { href: "/trenchless-sewer-repair" }, kids: ["Trenchless replacement"] },
            " can work if your pipe's condition and layout allow for it, meaning little to no digging beyond small access points. If the damage is too extensive, traditional excavation may be the better option. We'll assess your line on camera and explain which one actually fits before recommending either.",
          ],
        },
        {
          q: "How much does sewer line replacement typically cost?",
          preview: "We don't publish pricing since it depends heavily on your situation, the pipe's material, how deep it's buried, the length of the run, and whether trenchless or excavation makes sense for your property.",
          full: "We don't publish pricing since it depends heavily on your situation, the pipe's material, how deep it's buried, the length of the run, and whether trenchless or excavation makes sense for your property. Give us a call and we'll walk you through it after a camera inspection.",
        },
        {
          q: "What are the signs I need a full replacement, not just a repair?",
          preview: "A few signs point toward full replacement: repairs on the same section that keep failing, cracking or root intrusion spread across most of the line, or a pipe that's already collapsed or offset.",
          full: "A few signs point toward full replacement: repairs on the same section that keep failing, cracking or root intrusion spread across most of the line, or a pipe that's already collapsed or offset. Isolated damage usually just needs a repair. We'll confirm which one you're dealing with on camera before recommending anything.",
        },
      ],
    },
    {
      kind: "final",
      order: 90,
      heading: "Ready to Stop Worrying About Your Sewer Line?",
      body: "We've been fixing sewer lines for over 30 years, and we'll tell you exactly what's wrong before we touch anything. One call gets it handled.",
    },
  ],
  rail: { financingOrder: 35 },
  videoSchema: {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "Meet J. Blanton Plumbing",
    description: "J. Blanton Plumbing delivers fast, reliable, same-day plumbing service across Chicago and the surrounding suburbs.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZDFzUtjBUCk/maxresdefault.jpg",
    uploadDate: "2025-05-21T07:47:39-07:00",
    duration: "PT47S",
    contentUrl: "https://www.youtube.com/watch?v=ZDFzUtjBUCk",
    embedUrl: "https://www.youtube.com/embed/ZDFzUtjBUCk",
  },
};
