import type { SewerServicePage } from './types';

/**
 * Brief 200 — /sewer-maintenance, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/sewer-maintenance/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const SEWER_MAINTENANCE: SewerServicePage = {
  slug: "sewer-maintenance",
  meta: {
    title: "Sewer Line Maintenance",
    description: "We inspect your line, show you the camera footage, and tell you the truth, no manufactured urgency. Schedule your sewer checkup today.",
  },
  hero: {
    crumb: "Sewer Line Maintenance",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Line Maintenance",
    intro: "Regular checkups catch small problems before they turn into big, expensive ones. We tell you the truth about what's going on with your line, no manufactured urgency.",
    image: {
      src: "/images/services/sewer/sewer-cleanout-camera-maintenance.webp",
      alt: "J. Blanton plumber opening an outdoor sewer cleanout in a front yard, with the sewer camera reel ready beside him",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "why-maintenance",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Prevention Pays Off"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Why Does Sewer Line Maintenance Matter?"],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:0 0 20px;max-width:66ch",
          kids: [
            "Sewer line maintenance catches problems while they're still small and prevents them from becoming expensive fixes down the line. Here's what regular checkups can do for you:",
          ],
        },
        {
          tag: "ul",
          style: "list-style:none;margin:0 0 24px;padding:0;display:flex;flex-direction:column;gap:12px",
          kids: [
            {
              tag: "li",
              style: "display:flex;gap:12px;align-items:flex-start",
              kids: [
                {
                  tag: "span",
                  cls: "ndc-check",
                  style: "background:var(--c-carmine);flex-shrink:0;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-top:1px",
                  kids: [{ icon: "ndcCheck" }],
                },
                {
                  tag: "span",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Catch early root intrusion before it turns into a blockage."],
                },
              ],
            },
            {
              tag: "li",
              style: "display:flex;gap:12px;align-items:flex-start",
              kids: [
                {
                  tag: "span",
                  cls: "ndc-check",
                  style: "background:var(--c-carmine);flex-shrink:0;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-top:1px",
                  kids: [{ icon: "ndcCheck" }],
                },
                {
                  tag: "span",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Flag an aging or clay pipe before it cracks."],
                },
              ],
            },
            {
              tag: "li",
              style: "display:flex;gap:12px;align-items:flex-start",
              kids: [
                {
                  tag: "span",
                  cls: "ndc-check",
                  style: "background:var(--c-carmine);flex-shrink:0;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-top:1px",
                  kids: [{ icon: "ndcCheck" }],
                },
                {
                  tag: "span",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Stop a minor slow drain from turning into a full backup."],
                },
              ],
            },
            {
              tag: "li",
              style: "display:flex;gap:12px;align-items:flex-start",
              kids: [
                {
                  tag: "span",
                  cls: "ndc-check",
                  style: "background:var(--c-carmine);flex-shrink:0;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-top:1px",
                  kids: [{ icon: "ndcCheck" }],
                },
                {
                  tag: "span",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Keep a small fix from turning into a big one."],
                },
              ],
            },
          ],
        },
        {
          tag: "div",
          style: "background:var(--c-sand-50);border-left:5px solid var(--c-carmine);border-radius:10px;padding:18px 22px",
          kids: [
            {
              tag: "p",
              cls: "t-body-sm",
              style: "color:var(--c-midnight);margin:0",
              kids: [
                "Sewer line emergencies are among the most expensive plumbing problems a homeowner can face. Routine maintenance is the most cost-effective way to avoid them.",
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "how-often",
      tint: true,
      order: 20,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Maintenance Guidelines"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["How Often Does a Sewer Line Need Maintenance?"],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:0 0 28px;max-width:66ch",
          kids: [
            "How often your line needs a checkup depends mostly on your pipe's age and what's growing near it. Plumbers and home inspectors generally recommend:",
          ],
        },
        {
          tag: "div",
          style: "background:#FFFFFF;border-radius:14px;padding:clamp(16px,3vw,32px);box-shadow:0 4px 20px rgba(10,27,46,0.08)",
          kids: [
            {
              tag: "div",
              cls: "ss-compare-wrap",
              kids: [
                {
                  tag: "table",
                  cls: "ss-compare",
                  kids: [
                    {
                      tag: "thead",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "col" }, kids: ["Risk Tier"] },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Recommended Frequency"] },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Why"] },
                          ],
                        },
                      ],
                    },
                    {
                      tag: "tbody",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "th",
                              attrs: { scope: "row" },
                              kids: ["Older homes (clay, cast iron, or other aging pipe materials)"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Recommended Frequency" },
                              kids: ["At least once a year"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Why" },
                              kids: [
                                "These materials are more prone to cracking, shifting, and joint failure, especially as they age",
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "row" }, kids: ["Homes with mature trees nearby"] },
                            {
                              tag: "td",
                              attrs: { "data-label": "Recommended Frequency" },
                              kids: ["Every 1 to 2 years"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Why" },
                              kids: [
                                "Tree roots are the leading cause of sewer line blockages and work into small cracks over time",
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "th",
                              attrs: { scope: "row" },
                              kids: ["Newer homes (PVC or modern plastic pipe)"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Recommended Frequency" },
                              kids: ["Every 3 to 5 years"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Why" },
                              kids: [
                                "These materials resist roots and corrosion better, so less frequent checks are usually enough",
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:20px 0 0;max-width:66ch",
          kids: ["Not sure which category fits your home? A first inspection tells us exactly where you stand."],
        },
      ],
    },
    {
      kind: "panel",
      id: "whats-included",
      tint: false,
      order: 30,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["What's Included"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["What a Maintenance Visit Can (and Can't) Fix"],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:0 0 28px;max-width:66ch",
          kids: ["A maintenance visit is built around prevention, not repair. Here's where the line falls:"],
        },
        {
          tag: "div",
          style: "background:#FFFFFF;border-radius:14px;padding:clamp(16px,3vw,32px);box-shadow:0 4px 20px rgba(10,27,46,0.08)",
          kids: [
            {
              tag: "div",
              cls: "ss-compare-wrap",
              kids: [
                {
                  tag: "table",
                  cls: "ss-compare",
                  kids: [
                    {
                      tag: "thead",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            { tag: "th", attrs: { scope: "col" }, kids: ["Included in a Maintenance Visit"] },
                            { tag: "th", attrs: { scope: "col" }, kids: ["Needs a Different Service"] },
                          ],
                        },
                      ],
                    },
                    {
                      tag: "tbody",
                      kids: [
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Included in a Maintenance Visit" },
                              kids: ["A camera inspection to check your line's current condition"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Needs a Different Service" },
                              kids: [
                                "An active sewage backup",
                                { tag: "br" },
                                "Likely fix: ",
                                { phone: { kids: ["Emergency Service"] } },
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Included in a Maintenance Visit" },
                              kids: ["Catching early root growth or wear before it becomes a bigger problem"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Needs a Different Service" },
                              kids: [
                                "A cracked or collapsed pipe",
                                { tag: "br" },
                                "Likely fix: ",
                                { tag: "a", attrs: { href: "/sewer-repair" }, kids: ["Sewer Repair"] },
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Included in a Maintenance Visit" },
                              kids: ["A light interior clean as part of the visit"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Needs a Different Service" },
                              kids: [
                                "A heavy clog that needs full clearing",
                                { tag: "br" },
                                "Likely fix: ",
                                { tag: "a", attrs: { href: "/sewer-rodding" }, kids: ["Sewer Rodding"] },
                                " or ",
                                { tag: "a", attrs: { href: "/hydro-jetting" }, kids: ["Hydro Jetting"] },
                              ],
                            },
                          ],
                        },
                        {
                          tag: "tr",
                          kids: [
                            {
                              tag: "td",
                              attrs: { "data-label": "Included in a Maintenance Visit" },
                              kids: ["An honest assessment of what your line needs next"],
                            },
                            {
                              tag: "td",
                              attrs: { "data-label": "Needs a Different Service" },
                              kids: [
                                "A line that's reached the end of its lifespan",
                                { tag: "br" },
                                "Likely fix: ",
                                {
                                  tag: "a",
                                  attrs: { href: "/sewer-line-replacement" },
                                  kids: ["Sewer Replacement"],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: "p",
          cls: "t-body-sm pv-mute",
          style: "margin:20px 0 0;max-width:66ch",
          kids: [
            "If your line needs more than a checkup, we'll tell you exactly what and why. No surprise upsells.",
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-we-do-differently",
      tint: true,
      order: 40,
      body: [
        {
          tag: "div",
          cls: "ss-split rev",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:0 0 24px;max-width:66ch",
                  kids: ["What We Do Differently"],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["1. Camera Inspection"] },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "We run a camera down your line at every visit. You see the same footage we do, so you know your line's actual condition, not a guess.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["2. Honest Diagnosis"] },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "We'll tell you straight if everything looks good, or if something's starting to develop. We don't manufacture urgency to sell a bigger job when a scheduled check is all you need.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. Upfront Pricing"] },
                        {
                          tag: "p",
                          cls: "t-body-sm pv-mute",
                          style: "margin:0",
                          kids: [
                            "Once we know what your line needs, you get a flat rate before anything starts. A maintenance visit stays a maintenance visit, not a sales pitch for something bigger.",
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "video",
      tint: false,
      order: 50,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [{ video: { kind: "youtube", id: "ZDFzUtjBUCk", title: "Meet J. Blanton Plumbing" } }],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Meet J. Blanton"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Big Enough to Get the Job Done, Small Enough to Care"],
                },
                {
                  tag: "p",
                  cls: "t-body",
                  style: "color:var(--c-slate);margin:0;max-width:66ch",
                  kids: [
                    "We’ve grown a lot since 1993, but the way we work hasn’t changed. Here’s a closer look at who we are.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "reviews",
      order: 60,
      variant: "cap",
      eyebrow: "Customer Stories",
      heading: "Sewer Line Maintenance Reviews",
      items: [
        {
          quote: "\"We had Christian come for our home maintenance check and he was wonderful! I appreciated how thorough he was, that he provided me with feedback and notes for each potential issue he saw, and he even cleaned out a messy drain in my sink.\"",
          name: "Jeannie Smith",
          href: "https://maps.app.goo.gl/96wBa6YbYwQptVSS6",
        },
        {
          quote: "\"Christian M came out to do our annual service and was super helpful and friendly. I got to see the inside of our sewer access with a big snake camera and he walked me through everything that he was seeing.\"",
          name: "Alkan Sezginis",
          href: "https://maps.app.goo.gl/pWz1WmrZSV3Eg8Gz5",
        },
        {
          quote: "\"He rodded out the kitchen sink drain piping and fixed the leaks... In the end he offered us an excellent maintenance plan, which will definitely save us money and headaches in the future.\"",
          name: "Judith Schader",
          href: "https://maps.app.goo.gl/8sp2hFNkS7FD3Yp38",
        },
      ],
    },
    {
      kind: "faq",
      order: 70,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "How often should a sewer line be inspected or maintained?",
          preview: "It depends on your pipe's age and what's around it.",
          full: "It depends on your pipe's age and what's around it. Older pipes, like clay or cast iron, benefit from a check at least once a year. Homes with mature trees nearby should aim for every one to two years, since root intrusion is the most common cause of sewer line problems. Newer PVC lines can usually go three to five years between checks.",
        },
        {
          q: "What does a sewer maintenance visit actually include?",
          preview: "A maintenance visit starts with a camera inspection to check your line's current condition.",
          full: [
            "A maintenance visit starts with a ",
            { tag: "a", attrs: { href: "/sewer-camera-inspection" }, kids: ["camera inspection"] },
            " to check your line's current condition. From there, we give you an honest read on what we see, whether everything looks fine or something's starting to develop, along with a light interior clean as part of the visit. If something bigger turns up, we'll walk you through it before recommending any next steps.",
          ],
        },
        {
          q: "Does regular maintenance actually prevent expensive repairs?",
          preview: "Sewer line emergencies are some of the most expensive plumbing problems a homeowner can face, and most of them don't happen without warning.",
          full: "Sewer line emergencies are some of the most expensive plumbing problems a homeowner can face, and most of them don't happen without warning. Regular maintenance catches early signs, like root growth or a developing crack, while they're still a small, inexpensive fix instead of a big one.",
        },
        {
          q: "What's the difference between maintenance and repair?",
          preview: "Maintenance is scheduled and preventive: a camera inspection and light upkeep to catch problems early.",
          full: [
            "Maintenance is scheduled and preventive: a camera inspection and light upkeep to catch problems early. Repair is what happens once there's an actual issue, like a crack, a break, or a line that's already backing up. If your maintenance visit turns up something more serious, that's when ",
            { tag: "a", attrs: { href: "/sewer-repair" }, kids: ["a repair conversation"] },
            " starts.",
          ],
        },
      ],
    },
    {
      kind: "ndc",
      order: 80,
      body: "Prevent catastrophes before they disrupt your life. The No Drip Club ensures your waste and sewer lines are monitored and serviced regularly by our absolute best.",
    },
    { kind: "services", order: 90 },
    {
      kind: "final",
      order: 100,
      heading: "Ready to Stop Worrying About Your Sewer Line?",
      body: "We've been fixing sewer lines for over 30 years, and we'll tell you exactly what's wrong before we touch anything. One call gets it handled.",
    },
  ],
  rail: { financingOrder: 45 },
  videoSchema: {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "Meet J. Blanton Plumbing",
    description: "J. Blanton Plumbing delivers fast, reliable, same-day plumbing service across Chicago and the surrounding suburbs.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZDFzUtjBUCk/maxresdefault.jpg",
    uploadDate: "2025-05-21T07:47:39-07:00",
    duration: "PT47S",
    contentUrl: "https://www.youtube.com/watch?v=ZDFzUtjBUCk",
    embedUrl: "https://www.youtube.com/embed/ZDFzUtjBUCk",
  },
};
