import type { SewerServicePage } from './types';

/**
 * Brief 200 — /sewer-camera-inspection, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/sewer-camera-inspection/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const SEWER_CAMERA_INSPECTION: SewerServicePage = {
  slug: "sewer-camera-inspection",
  meta: {
    title: "Sewer Camera Inspection",
    description: "See exactly what our camera finds during your sewer camera inspection, before you decide anything. No sales pitch, just real answers.",
  },
  hero: {
    crumb: "Sewer Camera Inspection",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Camera Inspection",
    intro: "Get a clear look inside your line before a small issue turns into an expensive dig. Using waterproof cameras with strong LED lighting, we show you exactly what’s going on, so you can choose the right fix with confidence.",
    image: {
      src: "/images/services/sewer/sewer-camera-inspection-backyard.webp",
      alt: "Two J. Blanton plumbers watching the monitor of a sewer camera during a backyard sewer line inspection",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "common-reasons-to-get-a-sewer-camera-inspection",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Not Just for Problems"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["Common Reasons to Get a Sewer Camera Inspection"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 28px;max-width:66ch",
          kids: [
            "Homeowners aren’t always experiencing sewer line problems when booking a camera inspection. This service isn’t only for problems, it’s also used for preventative checks and for locating lost items.",
          ],
        },
        {
          tag: "div",
          style: "display:grid;grid-template-columns:repeat(auto-fit,minmax(min(260px,100%),1fr));gap:24px",
          kids: [
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Retrieving Valuables"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Dropping a ring down the drain doesn’t mean it’s lost forever. Our camera inspections can help you locate jewelry and other valuables inside the sewer line. It’s worth a look before you assume it’s gone for good.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Pre-purchase Inspections or Remodeling"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "We’ll assess the condition of your sewer line before you buy or sell a property. If you’re planning to remodel a kitchen or bathroom, a camera inspection will help you understand if your plumbing can handle the new fixtures before work starts.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Inspecting the Septic System"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    {
                      tag: "a",
                      style: "color:var(--c-carmine)",
                      attrs: { href: "/sewer-maintenance" },
                      kids: ["Routine checks"],
                    },
                    " help keep your plumbing system in good shape. A camera inspection can identify issues before they become major problems. If you’re planning two or more inspections a year, it’s worth looking into ",
                    {
                      tag: "a",
                      style: "color:var(--c-carmine)",
                      attrs: { href: "/no-drip-club" },
                      kids: ["our membership program"],
                    },
                    ".",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "how-your-sewer-line-lets-you-know-you-need-one",
      tint: true,
      order: 20,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "Water-stained basement floor and opened drywall after a sewer backup, a common warning sign of a sewer line problem",
                    src: "/images/services/sewer/sewer-camera-inspection/sewer-camera-inspection-know-the-signs.webp",
                    loading: "lazy",
                  },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Know the Signs"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["How Your Sewer Line Lets You Know You Need One"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 16px",
                  kids: [
                    "Not every inspection starts with a sewer line problem, but when it does, your sewer line was probably trying to warn you. Here’s what to watch for:",
                  ],
                },
                {
                  tag: "ul",
                  style: "margin:0;padding-left:20px;display:flex;flex-direction:column;gap:8px",
                  kids: [
                    {
                      tag: "li",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate)",
                      kids: ["Drains that clog or back up more than once"],
                    },
                    {
                      tag: "li",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate)",
                      kids: ["Sewage odors inside or outside your home"],
                    },
                    {
                      tag: "li",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate)",
                      kids: ["Water damage, unexplained moisture, or mold with no clear cause"],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "how-a-sewer-camera-inspection-works",
      tint: false,
      order: 30,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["No Digging Required"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["How a Sewer Camera Inspection Works"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 20px;max-width:66ch",
          kids: [
            "No digging required. Here’s exactly how we get eyes on your sewer line and what you walk away with.",
          ],
        },
        {
          tag: "div",
          style: "display:flex;flex-direction:column;gap:20px;margin-bottom:20px;max-width:66ch",
          kids: [
            {
              tag: "div",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["1. Where We Start"] },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "We start by locating your main drain cleanout, whether it’s inside or outside your home. That’s where the camera goes in: no digging, no cutting into walls or floors.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["2. What We Use"] },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "We send in a waterproof camera with strong LED lighting, built to travel through the pipe and send back a clear, real-time picture of what’s inside.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. What You See and Get"] },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "As the camera moves through the line, we watch the footage live and mark the exact location of anything we find: root intrusion, cracks, corrosion, blockages, pipe separation, or offset joints. We save the footage and give you a copy for your records.",
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: "div",
          style: "background:var(--c-cream);border-left:4px solid var(--c-carmine);border-radius:8px;padding:14px 18px;max-width:66ch",
          kids: [
            {
              tag: "p",
              cls: "t-body-sm",
              style: "color:var(--c-midnight);margin:0",
              kids: [
                "If a cleanout is hard to reach or blocked, we’ll tell you rather than force our way in or damage anything to get access.",
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-a-sewer-camera-inspection-can-reveal",
      tint: true,
      order: 40,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["What We Look For"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["What a Sewer Camera Inspection Can Reveal"],
        },
        {
          tag: "p",
          cls: "t-body",
          style: "color:var(--c-slate);margin:0 0 36px;max-width:70ch",
          kids: [
            "Every sewer line is different depending on what it’s made of and how it’s held up over the years. Here’s what the camera can identify.",
          ],
        },
        {
          tag: "div",
          cls: "rail-block",
          style: "margin-bottom:44px",
          kids: [
            {
              tag: "div",
              cls: "rail-head",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0", kids: ["Pipe Types We Inspect"] },
                {
                  tag: "div",
                  cls: "rail-nav",
                  kids: [
                    {
                      tag: "button",
                      cls: "rail-btn",
                      attrs: { type: "button", "data-rail-dir": "prev", "aria-label": "Scroll pipe types left" },
                      kids: [{ icon: "chevronLeft" }],
                    },
                    {
                      tag: "button",
                      cls: "rail-btn",
                      attrs: { type: "button", "data-rail-dir": "next", "aria-label": "Scroll pipe types right" },
                      kids: [{ icon: "chevronRight" }],
                    },
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "rail",
              attrs: { role: "list", "aria-label": "Pipe types", tabindex: "0" },
              kids: [
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Corroded cast iron sewer pipe interior",
                        src: "/images/services/sewer/pipe-conditions/cast_iron.webp",
                      },
                    },
                    { tag: "h4", cls: "t-h4", style: "margin:0 0 8px;font-size:17px", kids: ["Cast Iron"] },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "Common in older homes, built to last decades but corrodes and cracks from the inside as it ages.",
                      ],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "PVC sewer pipe interior",
                        src: "/images/services/sewer/pipe-conditions/pvc.webp",
                      },
                    },
                    { tag: "h4", cls: "t-h4", style: "margin:0 0 8px;font-size:17px", kids: ["PVC"] },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "Lightweight and resistant to corrosion, though it can still crack, sag, or separate at the joints.",
                      ],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Clay sewer pipe interior with root intrusion at a joint",
                        src: "/images/services/sewer/pipe-conditions/clay.webp",
                      },
                    },
                    { tag: "h4", cls: "t-h4", style: "margin:0 0 8px;font-size:17px", kids: ["Clay"] },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: ["Common in homes built before the 1980s, prone to root intrusion and cracked joints."],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Sewer pipe interior after a trenchless liner repair",
                        src: "/images/services/sewer/pipe-conditions/lined_pipe.webp",
                      },
                    },
                    { tag: "h4", cls: "t-h4", style: "margin:0 0 8px;font-size:17px", kids: ["Lined Pipe"] },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "A pipe that’s already been repaired with a liner. We check the lining itself for wear or new damage.",
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: "div",
          cls: "rail-block",
          style: "margin-bottom:44px",
          kids: [
            {
              tag: "div",
              cls: "rail-head",
              kids: [
                { tag: "h3", cls: "t-h4", style: "margin:0", kids: ["Common Problems We Find"] },
                {
                  tag: "div",
                  cls: "rail-nav",
                  kids: [
                    {
                      tag: "button",
                      cls: "rail-btn",
                      attrs: {
                        type: "button",
                        "data-rail-dir": "prev",
                        "aria-label": "Scroll common problems left",
                      },
                      kids: [{ icon: "chevronLeft" }],
                    },
                    {
                      tag: "button",
                      cls: "rail-btn",
                      attrs: {
                        type: "button",
                        "data-rail-dir": "next",
                        "aria-label": "Scroll common problems right",
                      },
                      kids: [{ icon: "chevronRight" }],
                    },
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "rail",
              attrs: { role: "list", "aria-label": "Common problems", tabindex: "0" },
              kids: [
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Tree roots grown into and blocking the inside of a residential sewer pipe",
                        src: "/images/services/sewer/pipe-conditions/root_intrusion.webp",
                      },
                    },
                    {
                      tag: "h4",
                      cls: "t-h4",
                      style: "margin:0 0 8px;font-size:17px",
                      kids: ["Root Intrusion"],
                    },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "Tree roots work through small cracks or loose joints and grow inside the line, restricting flow.",
                      ],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Standing water pooled in a low spot, or belly, of a sewer pipe",
                        src: "/images/services/sewer/pipe-conditions/standing_water.webp",
                      },
                    },
                    {
                      tag: "h4",
                      cls: "t-h4",
                      style: "margin:0 0 8px;font-size:17px",
                      kids: ["Belly / Standing Water"],
                    },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "A low spot in the line where water and waste collect instead of draining, usually from ground settling.",
                      ],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Cracks and breaks in a sewer pipe wall",
                        src: "/images/services/sewer/pipe-conditions/cracks.webp",
                      },
                    },
                    {
                      tag: "h4",
                      cls: "t-h4",
                      style: "margin:0 0 8px;font-size:17px",
                      kids: ["Cracks & Breaks"],
                    },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: ["Physical damage to the pipe wall, from age, ground movement, or nearby digging."],
                    },
                  ],
                },
                {
                  tag: "div",
                  cls: "card",
                  attrs: { role: "listitem" },
                  kids: [
                    {
                      tag: "img",
                      style: "width:calc(100% + 44px);height:150px;object-fit:cover;border-radius:14px 10px 0 0;margin:-22px -22px 16px -22px;display:block",
                      attrs: {
                        alt: "Two sections of sewer pipe pulled apart at a joint",
                        src: "/images/services/sewer/pipe-conditions/pipe_separation.webp",
                      },
                    },
                    {
                      tag: "h4",
                      cls: "t-h4",
                      style: "margin:0 0 8px;font-size:17px",
                      kids: ["Pipe Separation"],
                    },
                    {
                      tag: "p",
                      cls: "t-body-sm",
                      style: "color:var(--c-slate);margin:0",
                      kids: [
                        "Two sections of pipe have pulled apart at the joint, leaving a gap for waste and roots.",
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "what-happens-when-you-call-j-blanton",
      tint: false,
      order: 50,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [
                {
                  tag: "img",
                  style: "width:100%;height:auto;display:block;border-radius:14px",
                  attrs: {
                    alt: "J. Blanton plumber in shoe covers on a home's front steps with a sewer camera",
                    src: "/images/services/sewer/plumber-sewer-camera-front-steps.webp",
                    loading: "lazy",
                  },
                },
              ],
            },
            {
              tag: "div",
              kids: [
                {
                  tag: "span",
                  cls: "t-eyebrow",
                  style: "color:var(--c-carmine)",
                  kids: ["The J. Blanton Difference"],
                },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["What Happens When You Call J. Blanton"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0 0 24px;max-width:66ch",
                  kids: [
                    "We answer calls 24/7, even on weekends and holidays. Once you schedule a visit, your technician calls or texts on the way and shows up right around the promised time.",
                  ],
                },
                {
                  tag: "div",
                  style: "display:flex;flex-direction:column;gap:20px;margin-bottom:28px",
                  kids: [
                    {
                      tag: "div",
                      kids: [
                        {
                          tag: "h3",
                          cls: "t-h4",
                          style: "margin:0 0 6px",
                          kids: ["1. Knowledgeable Technicians"],
                        },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "Our technicians know sewer systems inside and out, and they’ll answer every question you have, honestly and in plain language, before, during, and after the inspection.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["2. The Right Equipment"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "We invest in our own camera equipment, so we’re never waiting on a rental company to get the right tool to your home.",
                          ],
                        },
                      ],
                    },
                    {
                      tag: "div",
                      kids: [
                        { tag: "h3", cls: "t-h4", style: "margin:0 0 6px", kids: ["3. Guaranteed Work"] },
                        {
                          tag: "p",
                          cls: "t-body-sm",
                          style: "color:var(--c-slate);margin:0",
                          kids: [
                            "We stand behind every job we perform. Every inspection is fully documented, so you always have proof of exactly what we found.",
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  phone: { cls: "btn btn-primary t-btn", kids: [{ icon: "phone18NoAria" }, { phoneNumber: true }] },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "see-why-homeowners-actually-book-a-sewer-camera-",
      tint: true,
      order: 60,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [{ video: { kind: "youtube", id: "ZDFzUtjBUCk", title: "Meet J. Blanton Plumbing" } }],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Meet J. Blanton"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Big Enough to Get the Job Done, Small Enough to Care"],
                },
                {
                  tag: "p",
                  cls: "t-body",
                  style: "color:var(--c-slate);margin:0;max-width:66ch",
                  kids: [
                    "We’ve grown a lot since 1993, but the way we work hasn’t changed. Here’s a closer look at who we are.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "reviews",
      order: 70,
      variant: "link",
      eyebrow: "Customer Stories",
      heading: "Sewer Camera Inspection Reviews",
      items: [
        {
          quote: "\"I had an exceptional experience with Andreas from J. Blanton Plumbing. He came out to perform a camera inspection of my sewer line and was incredibly professional, thorough, and knowledgeable. He took the time to walk me through everything on the screen, explained each detail clearly, and answered all my questions with patience and honesty. I've dealt with many service professionals over the years, and I can honestly say this was the best experience I've ever had. Andreas went above and beyond, and I couldn't be happier with the level of service he provided. Highly recommended.\"",
          name: "Jason Newman",
          href: "https://maps.app.goo.gl/dCYwmimDqjq4Ke9s7",
        },
        {
          quote: "\"Josh came out and was awesome! Hi communication was perfect!! Right around the promised time, he called and texted to let me know he was on his way and would arrive within the hour. 45 minutes later he arrived, inspected the issue, and walked me through what was needed and the price. He finished the work and showed me everything via camera and showed me an issue that could cause some additional repairs in the future. He was fast, thorough, and all on an early Saturday morning! Thank you Josh and J Banton!!\"",
          name: "Charli Petty",
          href: "https://maps.app.goo.gl/N11PRoitwRSoQ9ht8",
        },
        {
          quote: "\"Had a camera inspection of a clogged sewer drain by George. He was very helpful, polite, professional and informative. We ended up moving forward with a sewer trenchless liner service and look forward to a good experience for the main service.\"",
          name: "Tyler Ko",
          href: "https://maps.app.goo.gl/he5PCDkFqheoKPiy8",
        },
      ],
    },
    {
      kind: "faq",
      order: 80,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "How much does a sewer camera inspection cost?",
          preview: "Cost depends on the length of your line, access points, and what we find along the way.",
          full: "The cost of a sewer camera inspection depends on factors like the length of your line, how many access points we need to check, and what we find along the way. Give us a call and we’ll walk you through it.",
        },
        {
          q: "How long does a sewer camera inspection take?",
          preview: "It depends on the length of your line and what we find along the way.",
          full: "The length of your sewer line and what we find along the way determines how long an inspection takes. A shorter, clear line goes quickly, a longer or more complicated one takes more time.",
        },
        {
          q: "Will a sewer camera inspection damage my pipes or my property?",
          preview: "No. We access your line through an existing cleanout, so no digging or cutting is required.",
          full: "No. We access your line through an existing cleanout, so there’s no digging or cutting into walls or floors. If a cleanout is hard to reach, we’ll tell you rather than force our way in.",
        },
        {
          q: "What are the signs I need a sewer camera inspection?",
          preview: "Recurring backups, sewage odors, or unexplained water damage and mold are the main signs.",
          full: "Recurring drain backups, sewage odors, or unexplained water damage and mold are all signs it’s worth having your line inspected. A camera inspection shows us exactly what’s going on instead of guessing.",
        },
        {
          q: "What should I expect during a sewer camera inspection?",
          preview: "We locate your cleanout, send a camera through while you watch live, then give you a full report.",
          full: "We start by locating your main drain cleanout, then send a camera through the line while you watch the footage live. Afterward, we give you a report with photos, video, and the exact location of anything we found.",
        },
        {
          q: "Do I need a sewer camera inspection before buying or selling a home?",
          preview: "It’s a smart step. A camera inspection shows the real condition of the line before you buy or sell.",
          full: "It’s a smart step. A camera inspection shows you the real condition of the sewer line, so you know what you’re getting into before you buy or sell.",
        },
      ],
    },
    { kind: "ndc", order: 90 },
    { kind: "services", order: 100 },
    {
      kind: "final",
      order: 110,
      heading: "Ready to See What’s Really Going On Down There?",
      body: "We’ve inspected sewer lines for over 30 years, and we still start every job the same way: no guessing, no pressure. Give us a call and find out what’s really going on in your line.",
    },
  ],
  rail: { financingOrder: 55 },
  videoSchema: {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "Meet J. Blanton Plumbing",
    description: "J. Blanton Plumbing delivers fast, reliable, same-day plumbing service across Chicago and the surrounding suburbs.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZDFzUtjBUCk/maxresdefault.jpg",
    uploadDate: "2025-05-21T07:47:39-07:00",
    duration: "PT47S",
    contentUrl: "https://www.youtube.com/watch?v=ZDFzUtjBUCk",
    embedUrl: "https://www.youtube.com/embed/ZDFzUtjBUCk",
  },
};
