import type { SewerServicePage } from './types';

/**
 * Brief 200 — /sewer-line-installation, ported verbatim from the approved Sewer Ecosystem v2 package
 * (public/sewer-v2-test/sewer-line-installation/index.html, as deployed at bb59af8 — folder sha256 886b1517…fcae: Brief 197 Round 2 + the
 * 2026-10-05 photo follow-ups). Generated by the Brief 200 port script, then owned by hand.
 *
 * Copy is the approved copy: do not edit strings here without a brief. Panel bodies are a
 * typed content tree (see SewerNode in ./types) so no approved sentence was retyped; the
 * CMS follow-up brief maps them to fields. Phone links are `{ phone }` nodes rendered through
 * PhoneLink/PhoneNumber (WhatConverts DNI) — never write a literal tel: here.
 */
export const SEWER_LINE_INSTALLATION: SewerServicePage = {
  slug: "sewer-line-installation",
  meta: {
    title: "Sewer Line Installation",
    description: "New construction, an ADU conversion, or a property that's never had one. Find out if you need a new sewer line, and what the process involves.",
  },
  hero: {
    crumb: "Sewer Line Installation",
    eyebrow: "Serving Homeowners for 30+ years",
    heading: "Sewer Line Installation",
    intro: "New construction, room additions, ADU conversions, or a full system upgrade instead of another repair. Every line we install gets graded and inspected to meet code. The price we quote before we start is the price you pay.",
    image: {
      src: "/images/services/sewer/svc-sewer-install.webp",
      alt: "J. Blanton Plumbing technician gluing PVC pipe fittings in an excavated trench during a new sewer line installation",
    },
  },
  sections: [
    {
      kind: "panel",
      id: "scenarios",
      tint: false,
      order: 10,
      body: [
        { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Common Scenarios"] },
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:12px 0 16px;max-width:66ch",
          kids: ["When You Need a New Sewer Line Installed"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 28px;max-width:66ch",
          kids: [
            "Sewer line installation means a brand-new line, whether that's a first connection or a full system upgrade, not a repair to one you already have. Here's what that looks like:",
          ],
        },
        {
          tag: "div",
          style: "display:grid;grid-template-columns:repeat(auto-fit,minmax(min(260px,100%),1fr));gap:24px",
          kids: [
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["New Construction or an Addition"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Building a new structure or adding to your property means connecting to the sewer system for the first time. We plan that connection as part of the build, not an afterthought.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Converting to an ADU or Finishing a Basement"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Turning a garage or basement into livable space, or building an accessory dwelling unit, usually means adding fixtures that need their own sewer connection.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["A Property That's Never Had a Sewer Connection"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "Some properties still run on a septic system or were never connected to the city sewer at all. Getting a proper connection in place is installation, not a repair.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["A Plumber Told You It's Time for a Full System Upgrade"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "When a line has failed for good, patching it again isn't an option. A full system upgrade means a new line instead of patching the old one again.",
                  ],
                },
              ],
            },
            {
              tag: "div",
              cls: "bento-tile",
              kids: [
                {
                  tag: "h3",
                  cls: "t-label",
                  style: "color:var(--c-carmine);margin:0 0 12px",
                  kids: ["Re-Routing a Line That's in the Way"],
                },
                {
                  tag: "p",
                  cls: "t-body-sm",
                  style: "color:var(--c-slate);margin:0",
                  kids: [
                    "A new addition, garage, driveway, or pool built over your sewer line's current path means the line has to move, even if it's still in good shape. We run a new line along a route that works with your property as it is now.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "process",
      tint: true,
      order: 20,
      body: [
        {
          tag: "h2",
          cls: "t-h2",
          style: "margin:0 0 16px;max-width:66ch",
          kids: ["Our Sewer Line Installation Process"],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-slate);margin:0 0 20px;max-width:66ch",
          kids: [
            "A new sewer line touches your yard, your permits, and the city's approval before it's done. Here's how we handle each part:",
          ],
        },
        {
          tag: "ol",
          style: "margin:0 0 20px;padding-left:22px;display:flex;flex-direction:column;gap:12px",
          kids: [
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate);padding-left:6px",
              kids: [
                "We start by walking the site, checking what's already there, and mapping out where the new line needs to run.",
              ],
            },
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate);padding-left:6px",
              kids: [
                "We pull the required permits and handle the paperwork with your city or municipality, so it isn't something you have to sort out yourself.",
              ],
            },
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate);padding-left:6px",
              kids: ["We install the line using the method that fits your site and your yard."],
            },
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate);padding-left:6px",
              kids: [
                "Once it's in, we test the line and coordinate the required city inspection before we close everything up.",
              ],
            },
            {
              tag: "li",
              cls: "t-body-sm",
              style: "color:var(--c-slate);padding-left:6px",
              kids: [
                "We restore the site when the work's done, so you're not left with an open trench or a torn-up yard.",
              ],
            },
          ],
        },
        {
          tag: "p",
          cls: "t-body-sm",
          style: "color:var(--c-midnight);margin:0 0 24px;max-width:66ch;font-weight:700",
          kids: [
            "From the first look at your site to the city's final sign-off, you know what's happening and why at every step.",
          ],
        },
        {
          tag: "div",
          style: "background:#FDFAF6;border-left:5px solid var(--c-carmine);border-radius:10px;padding:18px 22px",
          kids: [
            {
              tag: "h3",
              cls: "t-label",
              style: "color:var(--c-carmine);margin:0 0 10px",
              kids: ["Every Installation Includes"],
            },
            {
              tag: "ul",
              style: "margin:0;padding-left:20px;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:6px 24px",
              kids: [
                {
                  tag: "li",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["A full site assessment before work is scheduled"],
                },
                {
                  tag: "li",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Permit handling with your city or municipality"],
                },
                {
                  tag: "li",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["The right method for your site and yard"],
                },
                {
                  tag: "li",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Installation to code"],
                },
                {
                  tag: "li",
                  cls: "t-body-sm",
                  style: "color:var(--c-midnight)",
                  kids: ["Testing before we backfill"],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "panel",
      id: "video",
      tint: false,
      order: 30,
      body: [
        {
          tag: "div",
          cls: "ss-split",
          kids: [
            {
              tag: "div",
              kids: [{ video: { kind: "youtube", id: "ZDFzUtjBUCk", title: "Meet J. Blanton Plumbing" } }],
            },
            {
              tag: "div",
              kids: [
                { tag: "span", cls: "t-eyebrow", style: "color:var(--c-carmine)", kids: ["Meet J. Blanton"] },
                {
                  tag: "h2",
                  cls: "t-h2",
                  style: "margin:12px 0 16px;max-width:66ch",
                  kids: ["Big Enough to Get the Job Done, Small Enough to Care"],
                },
                {
                  tag: "p",
                  cls: "t-body",
                  style: "color:var(--c-slate);margin:0;max-width:66ch",
                  kids: [
                    "We’ve grown a lot since 1993, but the way we work hasn’t changed. Here’s a closer look at who we are.",
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: "reviews",
      order: 40,
      variant: "cap",
      eyebrow: "Customer Stories",
      heading: "Sewer Line Installation Reviews",
      items: [
        {
          quote: "\"This was a complex installation and re-piping. Matt was helpful, answered my questions and did clean and well-executed piping. He was diligent and efficient and maintained a clean work area. Very impressed. I am a Property Manager for high rise office buildings and I witness a lot of tradesmen and their work. Matt gets an 'A' from me!\"",
          name: "William Moyer",
          href: "https://maps.app.goo.gl/qvrcqkMhebNrzBf77",
        },
        {
          quote: "\"Great experience, J Blanton scoped and lined our sewer and installed a cleanout, it was quick and easy.\"",
          name: "Hannah Burque",
          href: "https://maps.app.goo.gl/LDDBAeUMxb1u1JXZ8",
        },
        {
          quote: "\"The technicians and plumbers involved were prompt, friendly, courteous and explained everything with the sewer lining project[...] I recommend them with no reservations!\"",
          name: "Terrence Thompson",
          href: "https://maps.app.goo.gl/GgzucH8Yq3KqinEk7",
        },
      ],
    },
    {
      kind: "faq",
      order: 50,
      eyebrow: "Got Questions?",
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "How long does a residential sewer line installation take?",
          preview: "It depends on the scope, the method, and how deep the line needs to go.",
          full: "It depends on the scope, the method, and how deep the line needs to go. A straightforward first-time connection might take a day or two. A full re-route or a larger excavation job takes longer. We'll give you a real timeline once we've seen the site.",
        },
        {
          q: "What pipe material do you install?",
          preview: "The material depends on your site, the depth of the line, and what your local code requires.",
          full: "The material depends on your site, the depth of the line, and what your local code requires. We'll walk you through what's right for your property before any work starts.",
        },
        {
          q: "What's the difference between installation and replacement?",
          preview: "Installation covers new lines: a first connection, moving a line that's in the way, or putting in a full new system when patching an old one stopped being an option.",
          full: [
            "Installation covers new lines: a first connection, moving a line that's in the way, or putting in a full new system when patching an old one stopped being an option. Replacement is specific to swapping out a line that's already failed, without changing what it connects to. If you're not sure which applies to your situation, give us a call, or check our ",
            { tag: "a", attrs: { href: "/sewer-line-replacement" }, kids: ["Sewer Replacement"] },
            " page for more on that process.",
          ],
        },
        {
          q: "Is financing available for a new sewer line installation?",
          preview: "Yes.",
          full: "Yes. Financing as low as 0% is available for sewer line installation, so you don't have to pay the full cost upfront. Give us a call and we'll walk you through the options.",
        },
      ],
    },
    { kind: "ndc", order: 60 },
    { kind: "services", order: 70 },
    {
      kind: "final",
      order: 80,
      heading: "Ready to Get Your New Sewer Line Installed?",
      body: "We've been installing sewer lines for over 30 years, and we'll walk you through exactly what the job takes before we touch anything. One call gets it started.",
    },
  ],
  rail: { financingOrder: 25 },
  videoSchema: {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "Meet J. Blanton Plumbing",
    description: "J. Blanton Plumbing delivers fast, reliable, same-day plumbing service across Chicago and the surrounding suburbs.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZDFzUtjBUCk/maxresdefault.jpg",
    uploadDate: "2025-05-21T07:47:39-07:00",
    duration: "PT47S",
    contentUrl: "https://www.youtube.com/watch?v=ZDFzUtjBUCk",
    embedUrl: "https://www.youtube.com/embed/ZDFzUtjBUCk",
  },
};
