/**
 * Brief 171, Track C1 — generate `src/lib/content/locator-index.generated.ts`,
 * the city → dispatching-office lookup the homepage store locator searches.
 *
 * ─── Why this is generated instead of imported ─────────────────────────────
 * The locator's search box needs to answer "which office serves Palatine?" in
 * the browser. That answer already exists — `getOfficeKey(slug)` in
 * `src/lib/content/cities/index.ts` maps all 386 registry entries onto 13
 * dispatch office keys. But `CITY_REGISTRY` is ASSEMBLED FROM THE CITY COPY
 * FILES: it imports `ALGONQUIN`, `ELGIN`, `EVANSTON`, `COLUMBUS` and the whole
 * Ohio template content module. Importing it (or `getOfficeKey`) from a client
 * component would drag every one of those prose files into the homepage's
 * JavaScript bundle — hundreds of KB of copy, to answer a question that reduces
 * to 386 three-string tuples.
 *
 * So the mapping is flattened here, at build time, in Node, where importing the
 * registry is free. The emitted file contains NOTHING but the tuple array: no
 * imports, no re-exported types, no prose. That is what makes it safe for
 * `StoreLocatorPanel` to `await import()` as its own webpack chunk.
 *
 * ─── Drift is a build failure, not a stale file ────────────────────────────
 * A generated file checked into the repo goes stale the moment someone
 * registers city 387. `scripts/check-locator-index.ts` regenerates this content
 * in memory and exits non-zero if it differs from what is committed — same
 * discipline as `check-ohio-slug-collisions.ts`. `renderIndex()` is exported
 * for exactly that purpose, so the two scripts cannot disagree about the format.
 *
 * Run:  npm run build:locator-index
 */
import { writeFileSync } from 'fs';
import path from 'path';
import { CITY_REGISTRY, getOfficeKey } from '../src/lib/content/cities/index';

export const OUT_PATH = path.join(
  process.cwd(),
  'src',
  'lib',
  'content',
  'locator-index.generated.ts'
);

/**
 * The exact bytes of the generated module.
 *
 * Sorted by display name so the emitted diff is stable and reviewable: adding
 * one city changes one line, not the whole file. `JSON.stringify` on each string
 * rather than hand-quoting, because city names contain apostrophes
 * ("O'Fallon"-shaped names) that would otherwise break the literal.
 */
export function renderIndex(): string {
  const rows = CITY_REGISTRY.map(
    (c) => [c.slug, c.name, getOfficeKey(c.slug)] as const
  ).sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]));

  const offices = new Set(rows.map((r) => r[2]));

  const lines = [
    '/**',
    ' * GENERATED by scripts/build-locator-index.ts — DO NOT HAND-EDIT.',
    ' *',
    ` * ${rows.length} registered city pages, each mapped to the office slug that`,
    ` * dispatches it (${offices.size} distinct offices), sorted by display name.`,
    ' *',
    ' * This exists so the homepage store locator can search cities client-side',
    ' * WITHOUT importing CITY_REGISTRY, which pulls every city copy file into the',
    ' * bundle. `StoreLocatorPanel` loads this module lazily, on first interaction',
    ' * with the search input, so it is its own chunk and never downloads for a',
    ' * visitor who only scrolls past.',
    ' *',
    ' * Regenerate with `npm run build:locator-index`.',
    ' * `npm run check:locator-index` fails if this file has drifted from the registry.',
    ' */',
    'export const LOCATOR_INDEX: readonly (readonly [slug: string, name: string, office: string])[] = [',
    ...rows.map(
      (r) => `  [${JSON.stringify(r[0])}, ${JSON.stringify(r[1])}, ${JSON.stringify(r[2])}],`
    ),
    '];',
    '',
  ];
  return lines.join('\n');
}

function main(): void {
  const content = renderIndex();
  writeFileSync(OUT_PATH, content, 'utf8');
  const count = content.split('\n').filter((l) => l.startsWith('  [')).length;
  console.log(
    `Wrote ${path.relative(process.cwd(), OUT_PATH)} — ${count} entries, ` +
      `${(Buffer.byteLength(content) / 1024).toFixed(1)} KB.`
  );
}

if (require.main === module) main();
