/**
 * Hand-maintained alias 301s (Brief 152, Fix 2).
 *
 * This is the file to edit when a slug is corrected or consolidated. It is the
 * counterpart to `legacy-redirect-map.json`, which is GENERATED from the
 * WordPress export and must never be hand-edited:
 *
 *   legacy-redirect-map.json  →  ~6,200 indexed WordPress URLs, regenerated by
 *                                scripts/build-legacy-redirect-map.ts
 *   THIS FILE                 →  decisions made after the migration: a slug that
 *                                was renamed, a page that was consolidated into
 *                                another, an alias marketing wants to keep alive
 *
 * Both are read through `lookupRedirect()` (src/lib/redirects/lookup.ts), so a
 * one-line addition here is live everywhere the lookup runs — including the
 * trailing-slash normalizer, which resolves `/alias/` straight to the final
 * target in a SINGLE hop instead of bouncing through `/alias`.
 *
 * RULES for entries:
 *  - Keys and values are normalized paths: lowercase, leading slash, NO trailing
 *    slash. (WordPress redirect targets carry trailing slashes — strip them. The
 *    new site's canonical form has none, and redirecting to a slashed URL would
 *    bounce back through the normalizer and create a two-hop chain.)
 *  - A target must be a URL that returns 200. Never point at another redirect
 *    source: `scripts/validate-sitemap.ts` fails the build on a chain.
 *  - Never add a key that the build actually serves — that would redirect a
 *    working page away. The same validator checks this.
 */
import { CITY_SLUG_TO_HUB_ALIAS, hasSubServiceRoute } from '@/lib/content/service-taxonomy';

/**
 * One-off slug corrections and consolidations.
 *
 * `/bathroom-plumbing` is the WordPress Redirection plugin's only public rule
 * (export `redirection-jblantonplumbing-com-august-3-2026.json`, id 1 + id 2,
 * 124 recorded hits). Its recorded target was `/bathroom-plumbing-chicago/`;
 * the trailing slash is stripped per the rule above. It is also present in the
 * generated map with the same target — kept here because THIS file is where a
 * human looks for it, and the validator asserts the two never disagree.
 *
 * `/hoa-line-piping` is the Brief 124 slug that Brief 125 superseded with
 * `/hoa-pipe-lining`. It hard-404'd until now while still being advertised in
 * sitemap.xml (Brief 152, Fixes 2.4 + 3).
 */
export const MANUAL_ALIAS_REDIRECTS: Readonly<Record<string, string>> = {
  '/bathroom-plumbing': '/bathroom-plumbing-chicago',
  '/hoa-line-piping': '/hoa-pipe-lining',
};

/**
 * Alias 301s DERIVED from `CITY_SLUG_TO_HUB_ALIAS` — the map that already
 * declares "this service slug's hub page lives at a different slug". Every key
 * in it is, by definition, a slug the site links FROM and serves nothing AT:
 * `/clogged-drains`, `/drain-cleaning` and `/gas-fireplace` all hard-404'd on
 * production (verified in the Brief 152 audit) even though the correct target
 * was sitting in that map the whole time. The other four keys happened to be in
 * the generated WordPress map and so already 301'd — the difference was luck,
 * not design.
 *
 * Deriving them means a future alias needs NO addition here at all: adding the
 * taxonomy entry (which you must do anyway for the menu and breadcrumbs to
 * resolve) also creates its 301.
 *
 * Guard: an alias key that IS a real top-level route is skipped, so promoting a
 * slug to its own page can never redirect that new page away.
 */
export const DERIVED_HUB_ALIAS_REDIRECTS: Readonly<Record<string, string>> =
  Object.freeze(
    Object.fromEntries(
      Object.entries(CITY_SLUG_TO_HUB_ALIAS)
        .filter(([alias, hub]) => alias !== hub && !hasSubServiceRoute(alias))
        .map(([alias, hub]) => [`/${alias}`, `/${hub}`])
    )
  );

/**
 * The merged alias map. Manual entries win, so a one-off correction can always
 * override the taxonomy-derived default.
 */
export const ALIAS_REDIRECTS: Readonly<Record<string, string>> = Object.freeze({
  ...DERIVED_HUB_ALIAS_REDIRECTS,
  ...MANUAL_ALIAS_REDIRECTS,
});
