/**
 * Hand-maintained alias 301s (Brief 152, Fix 2).
 *
 * This is the file to edit when a slug is corrected or consolidated. It is the
 * counterpart to `legacy-redirect-map.json`, which is GENERATED from the
 * WordPress export and must never be hand-edited:
 *
 *   legacy-redirect-map.json  →  ~6,200 indexed WordPress URLs, regenerated by
 *                                scripts/build-legacy-redirect-map.ts
 *   THIS FILE                 →  decisions made after the migration: a slug that
 *                                was renamed, a page that was consolidated into
 *                                another, an alias marketing wants to keep alive
 *
 * Both are read through `lookupRedirect()` (src/lib/redirects/lookup.ts), so a
 * one-line addition here is live everywhere the lookup runs — including the
 * trailing-slash normalizer, which resolves `/alias/` straight to the final
 * target in a SINGLE hop instead of bouncing through `/alias`.
 *
 * RULES for entries:
 *  - Keys and values are normalized paths: lowercase, leading slash, NO trailing
 *    slash. (WordPress redirect targets carry trailing slashes — strip them. The
 *    new site's canonical form has none, and redirecting to a slashed URL would
 *    bounce back through the normalizer and create a two-hop chain.)
 *  - A target must be a URL that returns 200. Never point at another redirect
 *    source: `scripts/validate-sitemap.ts` fails the build on a chain.
 *  - Never add a key that the build actually serves — that would redirect a
 *    working page away. The same validator checks this.
 */
import { CITY_SLUG_TO_HUB_ALIAS, hasSubServiceRoute } from '@/lib/content/service-taxonomy';

/**
 * One-off slug corrections and consolidations.
 *
 * `/bathroom-plumbing` is the WordPress Redirection plugin's only public rule
 * (export `redirection-jblantonplumbing-com-august-3-2026.json`, id 1 + id 2,
 * 124 recorded hits). Its recorded target was `/bathroom-plumbing-chicago/`;
 * the trailing slash is stripped per the rule above. It is also present in the
 * generated map with the same target — kept here because THIS file is where a
 * human looks for it, and the validator asserts the two never disagree.
 *
 * `/hoa-line-piping` is the Brief 124 slug that Brief 125 superseded with
 * `/hoa-pipe-lining`. It hard-404'd until now while still being advertised in
 * sitemap.xml (Brief 152, Fixes 2.4 + 3).
 */
export const MANUAL_ALIAS_REDIRECTS: Readonly<Record<string, string>> = {
  '/bathroom-plumbing': '/bathroom-plumbing-chicago',
  '/hoa-line-piping': '/hoa-pipe-lining',

  /* ── Brief 153, Track D — the residual 404 batch ───────────────────────────
   * Every entry below is a URL Google is still holding from
   * `seo-audit/residual-404s.csv`. The two-segment `/{city}/…` shapes are NOT
   * here: they are derived by `src/lib/redirects/city-scoped.ts`.
   *
   * Targets are the FINAL destination, never an intermediate. `/water-testing-2`
   * points at `/water-filtration-systems` rather than `/water-testing`, and the
   * two article artifacts point at `/knowledge-hub/{slug}` rather than the bare
   * slug, because those bases are themselves 301s and routing through them
   * would be a two-hop chain — which `scripts/validate-sitemap.ts` fails on.
   */

  // WordPress duplicate-slug artifacts (the single-segment four). A derived
  // "strip -2/-3" rule handles the six `/{city}/{service}-3` forms, but could
  // not handle these: `/catch-basin` is a hard 404 and `/water-testing` is
  // itself a redirect, so a derived rule would emit a broken target and a chain.
  '/catch-basin-2': '/services/drain', // /catch-basin does not exist; catch-basin is a drain service
  '/thank-you-2': '/thank-you',
  '/emergency-plumbing-2': '/emergency-plumbing',
  '/water-testing-2': '/water-filtration-systems', // direct — /water-testing is a 301

  // Legacy one-offs with a clear current equivalent.
  '/blog/category/plumbing': '/knowledge-hub', // WP category archive; the hub is the only index
  '/baths': '/bathroom-plumbing-chicago',
  '/meet-our-team': '/why-j-blanton', // the about/team page on the new site
  '/schedule-service': '/contact', // matches the existing /booking → /contact rule

  // URL-encoding artifacts. Both the raw and the percent-encoded form are
  // listed because whether middleware sees `&`/`'` decoded depends on the
  // client, and `normalizePath()` only lowercases and strips slashes.
  '/faucet-installation-&-repair': '/services/plumbing', // no top-level faucet route; plumbing is its category
  '/faucet-installation-%26-repair': '/services/plumbing',
  "/45443-5-signs-it's-time-to-replace-a-water-heater-in-mchenry":
    '/knowledge-hub/45443-5-signs-its-time-to-replace-a-water-heater-in-mchenry',
  '/45443-5-signs-it%27s-time-to-replace-a-water-heater-in-mchenry':
    '/knowledge-hub/45443-5-signs-its-time-to-replace-a-water-heater-in-mchenry',

  // WordPress feed URL for an article that migrated to the Knowledge Hub.
  '/how-to-install-plumbing-for-kitchen-sink/feed':
    '/knowledge-hub/how-to-install-plumbing-for-kitchen-sink',
};

/**
 * Brief 153, Track D — URLs deliberately LEFT as a clean 404, recorded here so
 * the decision is visible next to the ones that were redirected. A 404 is a
 * legitimate answer; inventing a destination to avoid one produces soft-404s
 * and dilutes the redirects that mean something.
 *
 *   /default.aspx                  ASP.NET convention; this site has never run
 *                                  on that stack. Scanner traffic.
 *   /index                         Same class — a directory-index convention,
 *                                  not a URL this site ever served.
 *   /lander                        Generic landing-page artifact with no
 *                                  matching page in the WordPress export.
 *   /wp-content/themes/jb-blanton/*  A literal asterisk. Not a URL.
 *   /media/mp4/*.mp4               Nine stray asset paths under five different
 *   /assets/content/v/*.mp4        prefixes, all carrying third-party video
 *   /assets/mp4/v/*.mp4            player query strings (`?vpe_id=`,
 *   /public/video/*.mp4            `?t={seek_to_start_number}`, `?view=player`).
 *   /resource/video_files/*.mp4    Grepped for in the Next repo, the WordPress
 *   /v/media/storage/*.mp4         theme AND the full WordPress export: ZERO
 *                                  references in any of them. They are not page
 *                                  URLs and must never 301 to a page.
 */
export const DELIBERATE_404S: readonly string[] = [
  '/default.aspx',
  '/index',
  '/lander',
];

/**
 * Alias 301s DERIVED from `CITY_SLUG_TO_HUB_ALIAS` — the map that already
 * declares "this service slug's hub page lives at a different slug". Every key
 * in it is, by definition, a slug the site links FROM and serves nothing AT:
 * `/clogged-drains`, `/drain-cleaning` and `/gas-fireplace` all hard-404'd on
 * production (verified in the Brief 152 audit) even though the correct target
 * was sitting in that map the whole time. The other four keys happened to be in
 * the generated WordPress map and so already 301'd — the difference was luck,
 * not design.
 *
 * Deriving them means a future alias needs NO addition here at all: adding the
 * taxonomy entry (which you must do anyway for the menu and breadcrumbs to
 * resolve) also creates its 301.
 *
 * Guard: an alias key that IS a real top-level route is skipped, so promoting a
 * slug to its own page can never redirect that new page away.
 */
export const DERIVED_HUB_ALIAS_REDIRECTS: Readonly<Record<string, string>> =
  Object.freeze(
    Object.fromEntries(
      Object.entries(CITY_SLUG_TO_HUB_ALIAS)
        .filter(([alias, hub]) => alias !== hub && !hasSubServiceRoute(alias))
        .map(([alias, hub]) => [`/${alias}`, `/${hub}`])
    )
  );

/**
 * The merged alias map. Manual entries win, so a one-off correction can always
 * override the taxonomy-derived default.
 */
export const ALIAS_REDIRECTS: Readonly<Record<string, string>> = Object.freeze({
  ...DERIVED_HUB_ALIAS_REDIRECTS,
  ...MANUAL_ALIAS_REDIRECTS,
});
